/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FlashcardSession } from "./FlashcardSession";
import { FlashcardSessionCountArgs } from "./FlashcardSessionCountArgs";
import { FlashcardSessionFindManyArgs } from "./FlashcardSessionFindManyArgs";
import { FlashcardSessionFindUniqueArgs } from "./FlashcardSessionFindUniqueArgs";
import { CreateFlashcardSessionArgs } from "./CreateFlashcardSessionArgs";
import { UpdateFlashcardSessionArgs } from "./UpdateFlashcardSessionArgs";
import { DeleteFlashcardSessionArgs } from "./DeleteFlashcardSessionArgs";
import { FlashcardSessionEntryFindManyArgs } from "../../flashcardSessionEntry/base/FlashcardSessionEntryFindManyArgs";
import { FlashcardSessionEntry } from "../../flashcardSessionEntry/base/FlashcardSessionEntry";
import { FlashcardDeck } from "../../flashcardDeck/base/FlashcardDeck";
import { StudentProfile } from "../../studentProfile/base/StudentProfile";
import { FlashcardSessionService } from "../flashcardSession.service";
@graphql.Resolver(() => FlashcardSession)
export class FlashcardSessionResolverBase {
  constructor(protected readonly service: FlashcardSessionService) {}

  async _flashcardSessionsMeta(
    @graphql.Args() args: FlashcardSessionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FlashcardSession])
  async flashcardSessions(
    @graphql.Args() args: FlashcardSessionFindManyArgs
  ): Promise<FlashcardSession[]> {
    return this.service.flashcardSessions(args);
  }

  @graphql.Query(() => FlashcardSession, { nullable: true })
  async flashcardSession(
    @graphql.Args() args: FlashcardSessionFindUniqueArgs
  ): Promise<FlashcardSession | null> {
    const result = await this.service.flashcardSession(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FlashcardSession)
  async createFlashcardSession(
    @graphql.Args() args: CreateFlashcardSessionArgs
  ): Promise<FlashcardSession> {
    return await this.service.createFlashcardSession({
      ...args,
      data: {
        ...args.data,

        flashcardDeck: args.data.flashcardDeck
          ? {
              connect: args.data.flashcardDeck,
            }
          : undefined,

        studentProfile: args.data.studentProfile
          ? {
              connect: args.data.studentProfile,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => FlashcardSession)
  async updateFlashcardSession(
    @graphql.Args() args: UpdateFlashcardSessionArgs
  ): Promise<FlashcardSession | null> {
    try {
      return await this.service.updateFlashcardSession({
        ...args,
        data: {
          ...args.data,

          flashcardDeck: args.data.flashcardDeck
            ? {
                connect: args.data.flashcardDeck,
              }
            : undefined,

          studentProfile: args.data.studentProfile
            ? {
                connect: args.data.studentProfile,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FlashcardSession)
  async deleteFlashcardSession(
    @graphql.Args() args: DeleteFlashcardSessionArgs
  ): Promise<FlashcardSession | null> {
    try {
      return await this.service.deleteFlashcardSession(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [FlashcardSessionEntry], {
    name: "flashcardSessionEntries",
  })
  async findFlashcardSessionEntries(
    @graphql.Parent() parent: FlashcardSession,
    @graphql.Args() args: FlashcardSessionEntryFindManyArgs
  ): Promise<FlashcardSessionEntry[]> {
    const results = await this.service.findFlashcardSessionEntries(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => FlashcardDeck, {
    nullable: true,
    name: "flashcardDeck",
  })
  async getFlashcardDeck(
    @graphql.Parent() parent: FlashcardSession
  ): Promise<FlashcardDeck | null> {
    const result = await this.service.getFlashcardDeck(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => StudentProfile, {
    nullable: true,
    name: "studentProfile",
  })
  async getStudentProfile(
    @graphql.Parent() parent: FlashcardSession
  ): Promise<StudentProfile | null> {
    const result = await this.service.getStudentProfile(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
