/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsOptional,
  IsDate,
  ValidateNested,
  IsNumber,
  Min,
  Max,
  IsString,
  MaxLength,
} from "class-validator";

import { Type } from "class-transformer";
import { FlashcardDeckWhereUniqueInput } from "../../flashcardDeck/base/FlashcardDeckWhereUniqueInput";
import { FlashcardSessionEntryCreateNestedManyWithoutFlashcardSessionsInput } from "./FlashcardSessionEntryCreateNestedManyWithoutFlashcardSessionsInput";
import { StudentProfileWhereUniqueInput } from "../../studentProfile/base/StudentProfileWhereUniqueInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class FlashcardSessionCreateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  completed?: boolean | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endTime?: Date | null;

  @ApiProperty({
    required: false,
    type: () => FlashcardDeckWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FlashcardDeckWhereUniqueInput)
  @IsOptional()
  @Field(() => FlashcardDeckWhereUniqueInput, {
    nullable: true,
  })
  flashcardDeck?: FlashcardDeckWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () =>
      FlashcardSessionEntryCreateNestedManyWithoutFlashcardSessionsInput,
  })
  @ValidateNested()
  @Type(
    () => FlashcardSessionEntryCreateNestedManyWithoutFlashcardSessionsInput
  )
  @IsOptional()
  @Field(
    () => FlashcardSessionEntryCreateNestedManyWithoutFlashcardSessionsInput,
    {
      nullable: true,
    }
  )
  flashcardSessionEntries?: FlashcardSessionEntryCreateNestedManyWithoutFlashcardSessionsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  progress?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sessionType?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  shuffleMode?: boolean | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startTime?: Date | null;

  @ApiProperty({
    required: false,
    type: () => StudentProfileWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => StudentProfileWhereUniqueInput)
  @IsOptional()
  @Field(() => StudentProfileWhereUniqueInput, {
    nullable: true,
  })
  studentProfile?: StudentProfileWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  summaryStats?: InputJsonValue;
}

export { FlashcardSessionCreateInput as FlashcardSessionCreateInput };
