/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  FlashcardSession as PrismaFlashcardSession,
  FlashcardSessionEntry as PrismaFlashcardSessionEntry,
  FlashcardDeck as PrismaFlashcardDeck,
  StudentProfile as PrismaStudentProfile,
} from "@prisma/client";

export class FlashcardSessionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FlashcardSessionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.flashcardSession.count(args);
  }

  async flashcardSessions(
    args: Prisma.FlashcardSessionFindManyArgs
  ): Promise<PrismaFlashcardSession[]> {
    return this.prisma.flashcardSession.findMany(args);
  }
  async flashcardSession(
    args: Prisma.FlashcardSessionFindUniqueArgs
  ): Promise<PrismaFlashcardSession | null> {
    return this.prisma.flashcardSession.findUnique(args);
  }
  async createFlashcardSession(
    args: Prisma.FlashcardSessionCreateArgs
  ): Promise<PrismaFlashcardSession> {
    return this.prisma.flashcardSession.create(args);
  }
  async updateFlashcardSession(
    args: Prisma.FlashcardSessionUpdateArgs
  ): Promise<PrismaFlashcardSession> {
    return this.prisma.flashcardSession.update(args);
  }
  async deleteFlashcardSession(
    args: Prisma.FlashcardSessionDeleteArgs
  ): Promise<PrismaFlashcardSession> {
    return this.prisma.flashcardSession.delete(args);
  }

  async findFlashcardSessionEntries(
    parentId: string,
    args: Prisma.FlashcardSessionEntryFindManyArgs
  ): Promise<PrismaFlashcardSessionEntry[]> {
    return this.prisma.flashcardSession
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .flashcardSessionEntries(args);
  }

  async getFlashcardDeck(
    parentId: string
  ): Promise<PrismaFlashcardDeck | null> {
    return this.prisma.flashcardSession
      .findUnique({
        where: { id: parentId },
      })
      .flashcardDeck();
  }

  async getStudentProfile(
    parentId: string
  ): Promise<PrismaStudentProfile | null> {
    return this.prisma.flashcardSession
      .findUnique({
        where: { id: parentId },
      })
      .studentProfile();
  }
}
