/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FlashcardSessionService } from "../flashcardSession.service";
import { FlashcardSessionCreateInput } from "./FlashcardSessionCreateInput";
import { FlashcardSession } from "./FlashcardSession";
import { FlashcardSessionFindManyArgs } from "./FlashcardSessionFindManyArgs";
import { FlashcardSessionWhereUniqueInput } from "./FlashcardSessionWhereUniqueInput";
import { FlashcardSessionUpdateInput } from "./FlashcardSessionUpdateInput";
import { FlashcardSessionEntryFindManyArgs } from "../../flashcardSessionEntry/base/FlashcardSessionEntryFindManyArgs";
import { FlashcardSessionEntry } from "../../flashcardSessionEntry/base/FlashcardSessionEntry";
import { FlashcardSessionEntryWhereUniqueInput } from "../../flashcardSessionEntry/base/FlashcardSessionEntryWhereUniqueInput";

export class FlashcardSessionControllerBase {
  constructor(protected readonly service: FlashcardSessionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FlashcardSession })
  async createFlashcardSession(
    @common.Body() data: FlashcardSessionCreateInput
  ): Promise<FlashcardSession> {
    return await this.service.createFlashcardSession({
      data: {
        ...data,

        flashcardDeck: data.flashcardDeck
          ? {
              connect: data.flashcardDeck,
            }
          : undefined,

        studentProfile: data.studentProfile
          ? {
              connect: data.studentProfile,
            }
          : undefined,
      },
      select: {
        completed: true,
        createdAt: true,
        endTime: true,

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        id: true,
        progress: true,
        sessionType: true,
        shuffleMode: true,
        startTime: true,

        studentProfile: {
          select: {
            id: true,
          },
        },

        summaryStats: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FlashcardSession] })
  @ApiNestedQuery(FlashcardSessionFindManyArgs)
  async flashcardSessions(
    @common.Req() request: Request
  ): Promise<FlashcardSession[]> {
    const args = plainToClass(FlashcardSessionFindManyArgs, request.query);
    return this.service.flashcardSessions({
      ...args,
      select: {
        completed: true,
        createdAt: true,
        endTime: true,

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        id: true,
        progress: true,
        sessionType: true,
        shuffleMode: true,
        startTime: true,

        studentProfile: {
          select: {
            id: true,
          },
        },

        summaryStats: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FlashcardSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async flashcardSession(
    @common.Param() params: FlashcardSessionWhereUniqueInput
  ): Promise<FlashcardSession | null> {
    const result = await this.service.flashcardSession({
      where: params,
      select: {
        completed: true,
        createdAt: true,
        endTime: true,

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        id: true,
        progress: true,
        sessionType: true,
        shuffleMode: true,
        startTime: true,

        studentProfile: {
          select: {
            id: true,
          },
        },

        summaryStats: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FlashcardSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFlashcardSession(
    @common.Param() params: FlashcardSessionWhereUniqueInput,
    @common.Body() data: FlashcardSessionUpdateInput
  ): Promise<FlashcardSession | null> {
    try {
      return await this.service.updateFlashcardSession({
        where: params,
        data: {
          ...data,

          flashcardDeck: data.flashcardDeck
            ? {
                connect: data.flashcardDeck,
              }
            : undefined,

          studentProfile: data.studentProfile
            ? {
                connect: data.studentProfile,
              }
            : undefined,
        },
        select: {
          completed: true,
          createdAt: true,
          endTime: true,

          flashcardDeck: {
            select: {
              id: true,
            },
          },

          id: true,
          progress: true,
          sessionType: true,
          shuffleMode: true,
          startTime: true,

          studentProfile: {
            select: {
              id: true,
            },
          },

          summaryStats: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FlashcardSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFlashcardSession(
    @common.Param() params: FlashcardSessionWhereUniqueInput
  ): Promise<FlashcardSession | null> {
    try {
      return await this.service.deleteFlashcardSession({
        where: params,
        select: {
          completed: true,
          createdAt: true,
          endTime: true,

          flashcardDeck: {
            select: {
              id: true,
            },
          },

          id: true,
          progress: true,
          sessionType: true,
          shuffleMode: true,
          startTime: true,

          studentProfile: {
            select: {
              id: true,
            },
          },

          summaryStats: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/flashcardSessionEntries")
  @ApiNestedQuery(FlashcardSessionEntryFindManyArgs)
  async findFlashcardSessionEntries(
    @common.Req() request: Request,
    @common.Param() params: FlashcardSessionWhereUniqueInput
  ): Promise<FlashcardSessionEntry[]> {
    const query = plainToClass(
      FlashcardSessionEntryFindManyArgs,
      request.query
    );
    const results = await this.service.findFlashcardSessionEntries(params.id, {
      ...query,
      select: {
        bookmarked: true,
        createdAt: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        flashcardSession: {
          select: {
            id: true,
          },
        },

        id: true,
        microbitsMarked: true,
        rating: true,
        timeSpent: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/flashcardSessionEntries")
  async connectFlashcardSessionEntries(
    @common.Param() params: FlashcardSessionWhereUniqueInput,
    @common.Body() body: FlashcardSessionEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardSessionEntries: {
        connect: body,
      },
    };
    await this.service.updateFlashcardSession({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/flashcardSessionEntries")
  async updateFlashcardSessionEntries(
    @common.Param() params: FlashcardSessionWhereUniqueInput,
    @common.Body() body: FlashcardSessionEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardSessionEntries: {
        set: body,
      },
    };
    await this.service.updateFlashcardSession({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/flashcardSessionEntries")
  async disconnectFlashcardSessionEntries(
    @common.Param() params: FlashcardSessionWhereUniqueInput,
    @common.Body() body: FlashcardSessionEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardSessionEntries: {
        disconnect: body,
      },
    };
    await this.service.updateFlashcardSession({
      where: params,
      data,
      select: { id: true },
    });
  }
}
