/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssetCreateNestedManyWithoutCourseSubSectionsInput } from "./AssetCreateNestedManyWithoutCourseSubSectionsInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
  IsInt,
  Min,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { CourseSectionWhereUniqueInput } from "../../courseSection/base/CourseSectionWhereUniqueInput";
import { FlashcardDeckCreateNestedManyWithoutCourseSubSectionsInput } from "./FlashcardDeckCreateNestedManyWithoutCourseSubSectionsInput";

@InputType()
class CourseSubSectionCreateInput {
  @ApiProperty({
    required: false,
    type: () => AssetCreateNestedManyWithoutCourseSubSectionsInput,
  })
  @ValidateNested()
  @Type(() => AssetCreateNestedManyWithoutCourseSubSectionsInput)
  @IsOptional()
  @Field(() => AssetCreateNestedManyWithoutCourseSubSectionsInput, {
    nullable: true,
  })
  assets?: AssetCreateNestedManyWithoutCourseSubSectionsInput;

  @ApiProperty({
    required: false,
    type: () => CourseSectionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CourseSectionWhereUniqueInput)
  @IsOptional()
  @Field(() => CourseSectionWhereUniqueInput, {
    nullable: true,
  })
  courseSection?: CourseSectionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => FlashcardDeckCreateNestedManyWithoutCourseSubSectionsInput,
  })
  @ValidateNested()
  @Type(() => FlashcardDeckCreateNestedManyWithoutCourseSubSectionsInput)
  @IsOptional()
  @Field(() => FlashcardDeckCreateNestedManyWithoutCourseSubSectionsInput, {
    nullable: true,
  })
  flashcardDecks?: FlashcardDeckCreateNestedManyWithoutCourseSubSectionsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  icon?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isLocked?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isSample?: boolean | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  order?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { CourseSubSectionCreateInput as CourseSubSectionCreateInput };
