/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CourseSubSection } from "./CourseSubSection";
import { CourseSubSectionCountArgs } from "./CourseSubSectionCountArgs";
import { CourseSubSectionFindManyArgs } from "./CourseSubSectionFindManyArgs";
import { CourseSubSectionFindUniqueArgs } from "./CourseSubSectionFindUniqueArgs";
import { CreateCourseSubSectionArgs } from "./CreateCourseSubSectionArgs";
import { UpdateCourseSubSectionArgs } from "./UpdateCourseSubSectionArgs";
import { DeleteCourseSubSectionArgs } from "./DeleteCourseSubSectionArgs";
import { CourseSection } from "../../courseSection/base/CourseSection";
import { CourseSubSectionService } from "../courseSubSection.service";
@graphql.Resolver(() => CourseSubSection)
export class CourseSubSectionResolverBase {
  constructor(protected readonly service: CourseSubSectionService) {}

  async _courseSubSectionsMeta(
    @graphql.Args() args: CourseSubSectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CourseSubSection])
  async courseSubSections(
    @graphql.Args() args: CourseSubSectionFindManyArgs
  ): Promise<CourseSubSection[]> {
    return this.service.courseSubSections(args);
  }

  @graphql.Query(() => CourseSubSection, { nullable: true })
  async courseSubSection(
    @graphql.Args() args: CourseSubSectionFindUniqueArgs
  ): Promise<CourseSubSection | null> {
    const result = await this.service.courseSubSection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CourseSubSection)
  async createCourseSubSection(
    @graphql.Args() args: CreateCourseSubSectionArgs
  ): Promise<CourseSubSection> {
    return await this.service.createCourseSubSection({
      ...args,
      data: {
        ...args.data,

        courseSection: args.data.courseSection
          ? {
              connect: args.data.courseSection,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => CourseSubSection)
  async updateCourseSubSection(
    @graphql.Args() args: UpdateCourseSubSectionArgs
  ): Promise<CourseSubSection | null> {
    try {
      return await this.service.updateCourseSubSection({
        ...args,
        data: {
          ...args.data,

          courseSection: args.data.courseSection
            ? {
                connect: args.data.courseSection,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CourseSubSection)
  async deleteCourseSubSection(
    @graphql.Args() args: DeleteCourseSubSectionArgs
  ): Promise<CourseSubSection | null> {
    try {
      return await this.service.deleteCourseSubSection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => CourseSection, {
    nullable: true,
    name: "courseSection",
  })
  async getCourseSection(
    @graphql.Parent() parent: CourseSubSection
  ): Promise<CourseSection | null> {
    const result = await this.service.getCourseSection(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
