/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CourseSubSectionService } from "../courseSubSection.service";
import { CourseSubSectionCreateInput } from "./CourseSubSectionCreateInput";
import { CourseSubSection } from "./CourseSubSection";
import { CourseSubSectionFindManyArgs } from "./CourseSubSectionFindManyArgs";
import { CourseSubSectionWhereUniqueInput } from "./CourseSubSectionWhereUniqueInput";
import { CourseSubSectionUpdateInput } from "./CourseSubSectionUpdateInput";
import { AssetFindManyArgs } from "../../asset/base/AssetFindManyArgs";
import { Asset } from "../../asset/base/Asset";
import { AssetWhereUniqueInput } from "../../asset/base/AssetWhereUniqueInput";
import { FlashcardDeckFindManyArgs } from "../../flashcardDeck/base/FlashcardDeckFindManyArgs";
import { FlashcardDeck } from "../../flashcardDeck/base/FlashcardDeck";
import { FlashcardDeckWhereUniqueInput } from "../../flashcardDeck/base/FlashcardDeckWhereUniqueInput";

export class CourseSubSectionControllerBase {
  constructor(protected readonly service: CourseSubSectionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CourseSubSection })
  async createCourseSubSection(
    @common.Body() data: CourseSubSectionCreateInput
  ): Promise<CourseSubSection> {
    return await this.service.createCourseSubSection({
      data: {
        ...data,

        courseSection: data.courseSection
          ? {
              connect: data.courseSection,
            }
          : undefined,
      },
      select: {
        courseSection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        icon: true,
        id: true,
        isLocked: true,
        isSample: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CourseSubSection] })
  @ApiNestedQuery(CourseSubSectionFindManyArgs)
  async courseSubSections(
    @common.Req() request: Request
  ): Promise<CourseSubSection[]> {
    const args = plainToClass(CourseSubSectionFindManyArgs, request.query);
    return this.service.courseSubSections({
      ...args,
      select: {
        courseSection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        icon: true,
        id: true,
        isLocked: true,
        isSample: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CourseSubSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async courseSubSection(
    @common.Param() params: CourseSubSectionWhereUniqueInput
  ): Promise<CourseSubSection | null> {
    const result = await this.service.courseSubSection({
      where: params,
      select: {
        courseSection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        icon: true,
        id: true,
        isLocked: true,
        isSample: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CourseSubSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCourseSubSection(
    @common.Param() params: CourseSubSectionWhereUniqueInput,
    @common.Body() data: CourseSubSectionUpdateInput
  ): Promise<CourseSubSection | null> {
    try {
      return await this.service.updateCourseSubSection({
        where: params,
        data: {
          ...data,

          courseSection: data.courseSection
            ? {
                connect: data.courseSection,
              }
            : undefined,
        },
        select: {
          courseSection: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          icon: true,
          id: true,
          isLocked: true,
          isSample: true,
          order: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CourseSubSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCourseSubSection(
    @common.Param() params: CourseSubSectionWhereUniqueInput
  ): Promise<CourseSubSection | null> {
    try {
      return await this.service.deleteCourseSubSection({
        where: params,
        select: {
          courseSection: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          icon: true,
          id: true,
          isLocked: true,
          isSample: true,
          order: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/assets")
  @ApiNestedQuery(AssetFindManyArgs)
  async findAssets(
    @common.Req() request: Request,
    @common.Param() params: CourseSubSectionWhereUniqueInput
  ): Promise<Asset[]> {
    const query = plainToClass(AssetFindManyArgs, request.query);
    const results = await this.service.findAssets(params.id, {
      ...query,
      select: {
        courseSubSection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isSample: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/assets")
  async connectAssets(
    @common.Param() params: CourseSubSectionWhereUniqueInput,
    @common.Body() body: AssetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assets: {
        connect: body,
      },
    };
    await this.service.updateCourseSubSection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/assets")
  async updateAssets(
    @common.Param() params: CourseSubSectionWhereUniqueInput,
    @common.Body() body: AssetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assets: {
        set: body,
      },
    };
    await this.service.updateCourseSubSection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/assets")
  async disconnectAssets(
    @common.Param() params: CourseSubSectionWhereUniqueInput,
    @common.Body() body: AssetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assets: {
        disconnect: body,
      },
    };
    await this.service.updateCourseSubSection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/flashcardDecks")
  @ApiNestedQuery(FlashcardDeckFindManyArgs)
  async findFlashcardDecks(
    @common.Req() request: Request,
    @common.Param() params: CourseSubSectionWhereUniqueInput
  ): Promise<FlashcardDeck[]> {
    const query = plainToClass(FlashcardDeckFindManyArgs, request.query);
    const results = await this.service.findFlashcardDecks(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        courseSubSection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        isSample: true,
        lastUpdated: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/flashcardDecks")
  async connectFlashcardDecks(
    @common.Param() params: CourseSubSectionWhereUniqueInput,
    @common.Body() body: FlashcardDeckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardDecks: {
        connect: body,
      },
    };
    await this.service.updateCourseSubSection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/flashcardDecks")
  async updateFlashcardDecks(
    @common.Param() params: CourseSubSectionWhereUniqueInput,
    @common.Body() body: FlashcardDeckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardDecks: {
        set: body,
      },
    };
    await this.service.updateCourseSubSection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/flashcardDecks")
  async disconnectFlashcardDecks(
    @common.Param() params: CourseSubSectionWhereUniqueInput,
    @common.Body() body: FlashcardDeckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardDecks: {
        disconnect: body,
      },
    };
    await this.service.updateCourseSubSection({
      where: params,
      data,
      select: { id: true },
    });
  }
}
