/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssetUpdateManyWithoutCourseSubSectionsInput } from "./AssetUpdateManyWithoutCourseSubSectionsInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
  IsInt,
  Min,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { CourseSectionWhereUniqueInput } from "../../courseSection/base/CourseSectionWhereUniqueInput";
import { FlashcardDeckUpdateManyWithoutCourseSubSectionsInput } from "./FlashcardDeckUpdateManyWithoutCourseSubSectionsInput";

@InputType()
class CourseSubSectionUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AssetUpdateManyWithoutCourseSubSectionsInput,
  })
  @ValidateNested()
  @Type(() => AssetUpdateManyWithoutCourseSubSectionsInput)
  @IsOptional()
  @Field(() => AssetUpdateManyWithoutCourseSubSectionsInput, {
    nullable: true,
  })
  assets?: AssetUpdateManyWithoutCourseSubSectionsInput;

  @ApiProperty({
    required: false,
    type: () => CourseSectionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CourseSectionWhereUniqueInput)
  @IsOptional()
  @Field(() => CourseSectionWhereUniqueInput, {
    nullable: true,
  })
  courseSection?: CourseSectionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => FlashcardDeckUpdateManyWithoutCourseSubSectionsInput,
  })
  @ValidateNested()
  @Type(() => FlashcardDeckUpdateManyWithoutCourseSubSectionsInput)
  @IsOptional()
  @Field(() => FlashcardDeckUpdateManyWithoutCourseSubSectionsInput, {
    nullable: true,
  })
  flashcardDecks?: FlashcardDeckUpdateManyWithoutCourseSubSectionsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  icon?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isLocked?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isSample?: boolean | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  order?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { CourseSubSectionUpdateInput as CourseSubSectionUpdateInput };
