/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  CourseSubSection as PrismaCourseSubSection,
  CourseSection as PrismaCourseSection,
} from "@prisma/client";

export class CourseSubSectionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CourseSubSectionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.courseSubSection.count(args);
  }

  async courseSubSections(
    args: Prisma.CourseSubSectionFindManyArgs
  ): Promise<PrismaCourseSubSection[]> {
    return this.prisma.courseSubSection.findMany(args);
  }
  async courseSubSection(
    args: Prisma.CourseSubSectionFindUniqueArgs
  ): Promise<PrismaCourseSubSection | null> {
    return this.prisma.courseSubSection.findUnique(args);
  }
  async createCourseSubSection(
    args: Prisma.CourseSubSectionCreateArgs
  ): Promise<PrismaCourseSubSection> {
    return this.prisma.courseSubSection.create(args);
  }
  async updateCourseSubSection(
    args: Prisma.CourseSubSectionUpdateArgs
  ): Promise<PrismaCourseSubSection> {
    return this.prisma.courseSubSection.update(args);
  }
  async deleteCourseSubSection(
    args: Prisma.CourseSubSectionDeleteArgs
  ): Promise<PrismaCourseSubSection> {
    return this.prisma.courseSubSection.delete(args);
  }

  async getCourseSection(
    parentId: string
  ): Promise<PrismaCourseSection | null> {
    return this.prisma.courseSubSection
      .findUnique({
        where: { id: parentId },
      })
      .courseSection();
  }
}
