/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SavedContentService } from "../savedContent.service";
import { SavedContentCreateInput } from "./SavedContentCreateInput";
import { SavedContent } from "./SavedContent";
import { SavedContentFindManyArgs } from "./SavedContentFindManyArgs";
import { SavedContentWhereUniqueInput } from "./SavedContentWhereUniqueInput";
import { SavedContentUpdateInput } from "./SavedContentUpdateInput";

export class SavedContentControllerBase {
  constructor(protected readonly service: SavedContentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SavedContent })
  async createSavedContent(
    @common.Body() data: SavedContentCreateInput
  ): Promise<SavedContent> {
    return await this.service.createSavedContent({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SavedContent] })
  @ApiNestedQuery(SavedContentFindManyArgs)
  async savedContents(@common.Req() request: Request): Promise<SavedContent[]> {
    const args = plainToClass(SavedContentFindManyArgs, request.query);
    return this.service.savedContents({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SavedContent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async savedContent(
    @common.Param() params: SavedContentWhereUniqueInput
  ): Promise<SavedContent | null> {
    const result = await this.service.savedContent({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SavedContent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSavedContent(
    @common.Param() params: SavedContentWhereUniqueInput,
    @common.Body() data: SavedContentUpdateInput
  ): Promise<SavedContent | null> {
    try {
      return await this.service.updateSavedContent({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SavedContent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSavedContent(
    @common.Param() params: SavedContentWhereUniqueInput
  ): Promise<SavedContent | null> {
    try {
      return await this.service.deleteSavedContent({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
