/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SavedContent } from "./SavedContent";
import { SavedContentCountArgs } from "./SavedContentCountArgs";
import { SavedContentFindManyArgs } from "./SavedContentFindManyArgs";
import { SavedContentFindUniqueArgs } from "./SavedContentFindUniqueArgs";
import { DeleteSavedContentArgs } from "./DeleteSavedContentArgs";
import { SavedContentService } from "../savedContent.service";
@graphql.Resolver(() => SavedContent)
export class SavedContentResolverBase {
  constructor(protected readonly service: SavedContentService) {}

  async _savedContentsMeta(
    @graphql.Args() args: SavedContentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SavedContent])
  async savedContents(
    @graphql.Args() args: SavedContentFindManyArgs
  ): Promise<SavedContent[]> {
    return this.service.savedContents(args);
  }

  @graphql.Query(() => SavedContent, { nullable: true })
  async savedContent(
    @graphql.Args() args: SavedContentFindUniqueArgs
  ): Promise<SavedContent | null> {
    const result = await this.service.savedContent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SavedContent)
  async deleteSavedContent(
    @graphql.Args() args: DeleteSavedContentArgs
  ): Promise<SavedContent | null> {
    try {
      return await this.service.deleteSavedContent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
