/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, SavedContent as PrismaSavedContent } from "@prisma/client";

export class SavedContentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SavedContentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.savedContent.count(args);
  }

  async savedContents(
    args: Prisma.SavedContentFindManyArgs
  ): Promise<PrismaSavedContent[]> {
    return this.prisma.savedContent.findMany(args);
  }
  async savedContent(
    args: Prisma.SavedContentFindUniqueArgs
  ): Promise<PrismaSavedContent | null> {
    return this.prisma.savedContent.findUnique(args);
  }
  async createSavedContent(
    args: Prisma.SavedContentCreateArgs
  ): Promise<PrismaSavedContent> {
    return this.prisma.savedContent.create(args);
  }
  async updateSavedContent(
    args: Prisma.SavedContentUpdateArgs
  ): Promise<PrismaSavedContent> {
    return this.prisma.savedContent.update(args);
  }
  async deleteSavedContent(
    args: Prisma.SavedContentDeleteArgs
  ): Promise<PrismaSavedContent> {
    return this.prisma.savedContent.delete(args);
  }
}
