/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CoursePricingService } from "../coursePricing.service";
import { CoursePricingCreateInput } from "./CoursePricingCreateInput";
import { CoursePricing } from "./CoursePricing";
import { CoursePricingFindManyArgs } from "./CoursePricingFindManyArgs";
import { CoursePricingWhereUniqueInput } from "./CoursePricingWhereUniqueInput";
import { CoursePricingUpdateInput } from "./CoursePricingUpdateInput";

export class CoursePricingControllerBase {
  constructor(protected readonly service: CoursePricingService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CoursePricing })
  async createCoursePricing(
    @common.Body() data: CoursePricingCreateInput
  ): Promise<CoursePricing> {
    return await this.service.createCoursePricing({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CoursePricing] })
  @ApiNestedQuery(CoursePricingFindManyArgs)
  async coursePricings(
    @common.Req() request: Request
  ): Promise<CoursePricing[]> {
    const args = plainToClass(CoursePricingFindManyArgs, request.query);
    return this.service.coursePricings({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CoursePricing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async coursePricing(
    @common.Param() params: CoursePricingWhereUniqueInput
  ): Promise<CoursePricing | null> {
    const result = await this.service.coursePricing({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CoursePricing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCoursePricing(
    @common.Param() params: CoursePricingWhereUniqueInput,
    @common.Body() data: CoursePricingUpdateInput
  ): Promise<CoursePricing | null> {
    try {
      return await this.service.updateCoursePricing({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CoursePricing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCoursePricing(
    @common.Param() params: CoursePricingWhereUniqueInput
  ): Promise<CoursePricing | null> {
    try {
      return await this.service.deleteCoursePricing({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
