/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, CoursePricing as PrismaCoursePricing } from "@prisma/client";

export class CoursePricingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CoursePricingCountArgs, "select">
  ): Promise<number> {
    return this.prisma.coursePricing.count(args);
  }

  async coursePricings(
    args: Prisma.CoursePricingFindManyArgs
  ): Promise<PrismaCoursePricing[]> {
    return this.prisma.coursePricing.findMany(args);
  }
  async coursePricing(
    args: Prisma.CoursePricingFindUniqueArgs
  ): Promise<PrismaCoursePricing | null> {
    return this.prisma.coursePricing.findUnique(args);
  }
  async createCoursePricing(
    args: Prisma.CoursePricingCreateArgs
  ): Promise<PrismaCoursePricing> {
    return this.prisma.coursePricing.create(args);
  }
  async updateCoursePricing(
    args: Prisma.CoursePricingUpdateArgs
  ): Promise<PrismaCoursePricing> {
    return this.prisma.coursePricing.update(args);
  }
  async deleteCoursePricing(
    args: Prisma.CoursePricingDeleteArgs
  ): Promise<PrismaCoursePricing> {
    return this.prisma.coursePricing.delete(args);
  }
}
