/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CoursePricing } from "./CoursePricing";
import { CoursePricingCountArgs } from "./CoursePricingCountArgs";
import { CoursePricingFindManyArgs } from "./CoursePricingFindManyArgs";
import { CoursePricingFindUniqueArgs } from "./CoursePricingFindUniqueArgs";
import { DeleteCoursePricingArgs } from "./DeleteCoursePricingArgs";
import { CoursePricingService } from "../coursePricing.service";
@graphql.Resolver(() => CoursePricing)
export class CoursePricingResolverBase {
  constructor(protected readonly service: CoursePricingService) {}

  async _coursePricingsMeta(
    @graphql.Args() args: CoursePricingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CoursePricing])
  async coursePricings(
    @graphql.Args() args: CoursePricingFindManyArgs
  ): Promise<CoursePricing[]> {
    return this.service.coursePricings(args);
  }

  @graphql.Query(() => CoursePricing, { nullable: true })
  async coursePricing(
    @graphql.Args() args: CoursePricingFindUniqueArgs
  ): Promise<CoursePricing | null> {
    const result = await this.service.coursePricing(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CoursePricing)
  async deleteCoursePricing(
    @graphql.Args() args: DeleteCoursePricingArgs
  ): Promise<CoursePricing | null> {
    try {
      return await this.service.deleteCoursePricing(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
