/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  StudentProfile as PrismaStudentProfile,
  ErrorCard as PrismaErrorCard,
  FlashcardSession as PrismaFlashcardSession,
} from "@prisma/client";

export class StudentProfileServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.StudentProfileCountArgs, "select">
  ): Promise<number> {
    return this.prisma.studentProfile.count(args);
  }

  async studentProfiles(
    args: Prisma.StudentProfileFindManyArgs
  ): Promise<PrismaStudentProfile[]> {
    return this.prisma.studentProfile.findMany(args);
  }
  async studentProfile(
    args: Prisma.StudentProfileFindUniqueArgs
  ): Promise<PrismaStudentProfile | null> {
    return this.prisma.studentProfile.findUnique(args);
  }
  async createStudentProfile(
    args: Prisma.StudentProfileCreateArgs
  ): Promise<PrismaStudentProfile> {
    return this.prisma.studentProfile.create(args);
  }
  async updateStudentProfile(
    args: Prisma.StudentProfileUpdateArgs
  ): Promise<PrismaStudentProfile> {
    return this.prisma.studentProfile.update(args);
  }
  async deleteStudentProfile(
    args: Prisma.StudentProfileDeleteArgs
  ): Promise<PrismaStudentProfile> {
    return this.prisma.studentProfile.delete(args);
  }

  async findErrorCards(
    parentId: string,
    args: Prisma.ErrorCardFindManyArgs
  ): Promise<PrismaErrorCard[]> {
    return this.prisma.studentProfile
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .errorCards(args);
  }

  async findFlashcardSessions(
    parentId: string,
    args: Prisma.FlashcardSessionFindManyArgs
  ): Promise<PrismaFlashcardSession[]> {
    return this.prisma.studentProfile
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .flashcardSessions(args);
  }
}
