/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { StudentProfile } from "./StudentProfile";
import { StudentProfileCountArgs } from "./StudentProfileCountArgs";
import { StudentProfileFindManyArgs } from "./StudentProfileFindManyArgs";
import { StudentProfileFindUniqueArgs } from "./StudentProfileFindUniqueArgs";
import { CreateStudentProfileArgs } from "./CreateStudentProfileArgs";
import { UpdateStudentProfileArgs } from "./UpdateStudentProfileArgs";
import { DeleteStudentProfileArgs } from "./DeleteStudentProfileArgs";
import { ErrorCardFindManyArgs } from "../../errorCard/base/ErrorCardFindManyArgs";
import { ErrorCard } from "../../errorCard/base/ErrorCard";
import { StudentProfileService } from "../studentProfile.service";
@graphql.Resolver(() => StudentProfile)
export class StudentProfileResolverBase {
  constructor(protected readonly service: StudentProfileService) {}

  async _studentProfilesMeta(
    @graphql.Args() args: StudentProfileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [StudentProfile])
  async studentProfiles(
    @graphql.Args() args: StudentProfileFindManyArgs
  ): Promise<StudentProfile[]> {
    return this.service.studentProfiles(args);
  }

  @graphql.Query(() => StudentProfile, { nullable: true })
  async studentProfile(
    @graphql.Args() args: StudentProfileFindUniqueArgs
  ): Promise<StudentProfile | null> {
    const result = await this.service.studentProfile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StudentProfile)
  async createStudentProfile(
    @graphql.Args() args: CreateStudentProfileArgs
  ): Promise<StudentProfile> {
    return await this.service.createStudentProfile({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => StudentProfile)
  async updateStudentProfile(
    @graphql.Args() args: UpdateStudentProfileArgs
  ): Promise<StudentProfile | null> {
    try {
      return await this.service.updateStudentProfile({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => StudentProfile)
  async deleteStudentProfile(
    @graphql.Args() args: DeleteStudentProfileArgs
  ): Promise<StudentProfile | null> {
    try {
      return await this.service.deleteStudentProfile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [ErrorCard], { name: "errorCards" })
  async findErrorCards(
    @graphql.Parent() parent: StudentProfile,
    @graphql.Args() args: ErrorCardFindManyArgs
  ): Promise<ErrorCard[]> {
    const results = await this.service.findErrorCards(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
