/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  CourseSection as PrismaCourseSection,
  CourseSubSection as PrismaCourseSubSection,
  Course as PrismaCourse,
} from "@prisma/client";

export class CourseSectionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CourseSectionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.courseSection.count(args);
  }

  async courseSections(
    args: Prisma.CourseSectionFindManyArgs
  ): Promise<PrismaCourseSection[]> {
    return this.prisma.courseSection.findMany(args);
  }
  async courseSection(
    args: Prisma.CourseSectionFindUniqueArgs
  ): Promise<PrismaCourseSection | null> {
    return this.prisma.courseSection.findUnique(args);
  }
  async createCourseSection(
    args: Prisma.CourseSectionCreateArgs
  ): Promise<PrismaCourseSection> {
    return this.prisma.courseSection.create(args);
  }
  async updateCourseSection(
    args: Prisma.CourseSectionUpdateArgs
  ): Promise<PrismaCourseSection> {
    return this.prisma.courseSection.update(args);
  }
  async deleteCourseSection(
    args: Prisma.CourseSectionDeleteArgs
  ): Promise<PrismaCourseSection> {
    return this.prisma.courseSection.delete(args);
  }

  async findCourseSubSections(
    parentId: string,
    args: Prisma.CourseSubSectionFindManyArgs
  ): Promise<PrismaCourseSubSection[]> {
    return this.prisma.courseSection
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .courseSubSections(args);
  }

  async getCourse(parentId: string): Promise<PrismaCourse | null> {
    return this.prisma.courseSection
      .findUnique({
        where: { id: parentId },
      })
      .course();
  }
}
