/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CourseSectionService } from "../courseSection.service";
import { CourseSectionCreateInput } from "./CourseSectionCreateInput";
import { CourseSection } from "./CourseSection";
import { CourseSectionFindManyArgs } from "./CourseSectionFindManyArgs";
import { CourseSectionWhereUniqueInput } from "./CourseSectionWhereUniqueInput";
import { CourseSectionUpdateInput } from "./CourseSectionUpdateInput";
import { CourseSubSectionFindManyArgs } from "../../courseSubSection/base/CourseSubSectionFindManyArgs";
import { CourseSubSection } from "../../courseSubSection/base/CourseSubSection";
import { CourseSubSectionWhereUniqueInput } from "../../courseSubSection/base/CourseSubSectionWhereUniqueInput";

export class CourseSectionControllerBase {
  constructor(protected readonly service: CourseSectionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CourseSection })
  async createCourseSection(
    @common.Body() data: CourseSectionCreateInput
  ): Promise<CourseSection> {
    return await this.service.createCourseSection({
      data: {
        ...data,

        course: data.course
          ? {
              connect: data.course,
            }
          : undefined,
      },
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        icon: true,
        id: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CourseSection] })
  @ApiNestedQuery(CourseSectionFindManyArgs)
  async courseSections(
    @common.Req() request: Request
  ): Promise<CourseSection[]> {
    const args = plainToClass(CourseSectionFindManyArgs, request.query);
    return this.service.courseSections({
      ...args,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        icon: true,
        id: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CourseSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async courseSection(
    @common.Param() params: CourseSectionWhereUniqueInput
  ): Promise<CourseSection | null> {
    const result = await this.service.courseSection({
      where: params,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        icon: true,
        id: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CourseSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCourseSection(
    @common.Param() params: CourseSectionWhereUniqueInput,
    @common.Body() data: CourseSectionUpdateInput
  ): Promise<CourseSection | null> {
    try {
      return await this.service.updateCourseSection({
        where: params,
        data: {
          ...data,

          course: data.course
            ? {
                connect: data.course,
              }
            : undefined,
        },
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          icon: true,
          id: true,
          order: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CourseSection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCourseSection(
    @common.Param() params: CourseSectionWhereUniqueInput
  ): Promise<CourseSection | null> {
    try {
      return await this.service.deleteCourseSection({
        where: params,
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          icon: true,
          id: true,
          order: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/courseSubSections")
  @ApiNestedQuery(CourseSubSectionFindManyArgs)
  async findCourseSubSections(
    @common.Req() request: Request,
    @common.Param() params: CourseSectionWhereUniqueInput
  ): Promise<CourseSubSection[]> {
    const query = plainToClass(CourseSubSectionFindManyArgs, request.query);
    const results = await this.service.findCourseSubSections(params.id, {
      ...query,
      select: {
        courseSection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        icon: true,
        id: true,
        isLocked: true,
        isSample: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/courseSubSections")
  async connectCourseSubSections(
    @common.Param() params: CourseSectionWhereUniqueInput,
    @common.Body() body: CourseSubSectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseSubSections: {
        connect: body,
      },
    };
    await this.service.updateCourseSection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/courseSubSections")
  async updateCourseSubSections(
    @common.Param() params: CourseSectionWhereUniqueInput,
    @common.Body() body: CourseSubSectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseSubSections: {
        set: body,
      },
    };
    await this.service.updateCourseSection({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/courseSubSections")
  async disconnectCourseSubSections(
    @common.Param() params: CourseSectionWhereUniqueInput,
    @common.Body() body: CourseSubSectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseSubSections: {
        disconnect: body,
      },
    };
    await this.service.updateCourseSection({
      where: params,
      data,
      select: { id: true },
    });
  }
}
