/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CourseSection } from "./CourseSection";
import { CourseSectionCountArgs } from "./CourseSectionCountArgs";
import { CourseSectionFindManyArgs } from "./CourseSectionFindManyArgs";
import { CourseSectionFindUniqueArgs } from "./CourseSectionFindUniqueArgs";
import { CreateCourseSectionArgs } from "./CreateCourseSectionArgs";
import { UpdateCourseSectionArgs } from "./UpdateCourseSectionArgs";
import { DeleteCourseSectionArgs } from "./DeleteCourseSectionArgs";
import { CourseSubSectionFindManyArgs } from "../../courseSubSection/base/CourseSubSectionFindManyArgs";
import { CourseSubSection } from "../../courseSubSection/base/CourseSubSection";
import { Course } from "../../course/base/Course";
import { CourseSectionService } from "../courseSection.service";
@graphql.Resolver(() => CourseSection)
export class CourseSectionResolverBase {
  constructor(protected readonly service: CourseSectionService) {}

  async _courseSectionsMeta(
    @graphql.Args() args: CourseSectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CourseSection])
  async courseSections(
    @graphql.Args() args: CourseSectionFindManyArgs
  ): Promise<CourseSection[]> {
    return this.service.courseSections(args);
  }

  @graphql.Query(() => CourseSection, { nullable: true })
  async courseSection(
    @graphql.Args() args: CourseSectionFindUniqueArgs
  ): Promise<CourseSection | null> {
    const result = await this.service.courseSection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CourseSection)
  async createCourseSection(
    @graphql.Args() args: CreateCourseSectionArgs
  ): Promise<CourseSection> {
    return await this.service.createCourseSection({
      ...args,
      data: {
        ...args.data,

        course: args.data.course
          ? {
              connect: args.data.course,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => CourseSection)
  async updateCourseSection(
    @graphql.Args() args: UpdateCourseSectionArgs
  ): Promise<CourseSection | null> {
    try {
      return await this.service.updateCourseSection({
        ...args,
        data: {
          ...args.data,

          course: args.data.course
            ? {
                connect: args.data.course,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CourseSection)
  async deleteCourseSection(
    @graphql.Args() args: DeleteCourseSectionArgs
  ): Promise<CourseSection | null> {
    try {
      return await this.service.deleteCourseSection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [CourseSubSection], { name: "courseSubSections" })
  async findCourseSubSections(
    @graphql.Parent() parent: CourseSection,
    @graphql.Args() args: CourseSubSectionFindManyArgs
  ): Promise<CourseSubSection[]> {
    const results = await this.service.findCourseSubSections(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Course, {
    nullable: true,
    name: "course",
  })
  async getCourse(
    @graphql.Parent() parent: CourseSection
  ): Promise<Course | null> {
    const result = await this.service.getCourse(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
