/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Microbit } from "./Microbit";
import { MicrobitCountArgs } from "./MicrobitCountArgs";
import { MicrobitFindManyArgs } from "./MicrobitFindManyArgs";
import { MicrobitFindUniqueArgs } from "./MicrobitFindUniqueArgs";
import { CreateMicrobitArgs } from "./CreateMicrobitArgs";
import { UpdateMicrobitArgs } from "./UpdateMicrobitArgs";
import { DeleteMicrobitArgs } from "./DeleteMicrobitArgs";
import { Flashcard } from "../../flashcard/base/Flashcard";
import { MicrobitService } from "../microbit.service";
@graphql.Resolver(() => Microbit)
export class MicrobitResolverBase {
  constructor(protected readonly service: MicrobitService) {}

  async _microbitsMeta(
    @graphql.Args() args: MicrobitCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Microbit])
  async microbits(
    @graphql.Args() args: MicrobitFindManyArgs
  ): Promise<Microbit[]> {
    return this.service.microbits(args);
  }

  @graphql.Query(() => Microbit, { nullable: true })
  async microbit(
    @graphql.Args() args: MicrobitFindUniqueArgs
  ): Promise<Microbit | null> {
    const result = await this.service.microbit(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Microbit)
  async createMicrobit(
    @graphql.Args() args: CreateMicrobitArgs
  ): Promise<Microbit> {
    return await this.service.createMicrobit({
      ...args,
      data: {
        ...args.data,

        flashcard: args.data.flashcard
          ? {
              connect: args.data.flashcard,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Microbit)
  async updateMicrobit(
    @graphql.Args() args: UpdateMicrobitArgs
  ): Promise<Microbit | null> {
    try {
      return await this.service.updateMicrobit({
        ...args,
        data: {
          ...args.data,

          flashcard: args.data.flashcard
            ? {
                connect: args.data.flashcard,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Microbit)
  async deleteMicrobit(
    @graphql.Args() args: DeleteMicrobitArgs
  ): Promise<Microbit | null> {
    try {
      return await this.service.deleteMicrobit(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Flashcard, {
    nullable: true,
    name: "flashcard",
  })
  async getFlashcard(
    @graphql.Parent() parent: Microbit
  ): Promise<Flashcard | null> {
    const result = await this.service.getFlashcard(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
