/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Microbit as PrismaMicrobit,
  Flashcard as PrismaFlashcard,
} from "@prisma/client";

export class MicrobitServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.MicrobitCountArgs, "select">): Promise<number> {
    return this.prisma.microbit.count(args);
  }

  async microbits(
    args: Prisma.MicrobitFindManyArgs
  ): Promise<PrismaMicrobit[]> {
    return this.prisma.microbit.findMany(args);
  }
  async microbit(
    args: Prisma.MicrobitFindUniqueArgs
  ): Promise<PrismaMicrobit | null> {
    return this.prisma.microbit.findUnique(args);
  }
  async createMicrobit(
    args: Prisma.MicrobitCreateArgs
  ): Promise<PrismaMicrobit> {
    return this.prisma.microbit.create(args);
  }
  async updateMicrobit(
    args: Prisma.MicrobitUpdateArgs
  ): Promise<PrismaMicrobit> {
    return this.prisma.microbit.update(args);
  }
  async deleteMicrobit(
    args: Prisma.MicrobitDeleteArgs
  ): Promise<PrismaMicrobit> {
    return this.prisma.microbit.delete(args);
  }

  async getFlashcard(parentId: string): Promise<PrismaFlashcard | null> {
    return this.prisma.microbit
      .findUnique({
        where: { id: parentId },
      })
      .flashcard();
  }
}
