/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MicrobitService } from "../microbit.service";
import { MicrobitCreateInput } from "./MicrobitCreateInput";
import { Microbit } from "./Microbit";
import { MicrobitFindManyArgs } from "./MicrobitFindManyArgs";
import { MicrobitWhereUniqueInput } from "./MicrobitWhereUniqueInput";
import { MicrobitUpdateInput } from "./MicrobitUpdateInput";

export class MicrobitControllerBase {
  constructor(protected readonly service: MicrobitService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Microbit })
  async createMicrobit(
    @common.Body() data: MicrobitCreateInput
  ): Promise<Microbit> {
    return await this.service.createMicrobit({
      data: {
        ...data,

        flashcard: data.flashcard
          ? {
              connect: data.flashcard,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        feedback: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        forgetCount: true,
        highlightedText: true,
        id: true,
        reviewCount: true,
        text: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Microbit] })
  @ApiNestedQuery(MicrobitFindManyArgs)
  async microbits(@common.Req() request: Request): Promise<Microbit[]> {
    const args = plainToClass(MicrobitFindManyArgs, request.query);
    return this.service.microbits({
      ...args,
      select: {
        createdAt: true,
        feedback: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        forgetCount: true,
        highlightedText: true,
        id: true,
        reviewCount: true,
        text: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Microbit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async microbit(
    @common.Param() params: MicrobitWhereUniqueInput
  ): Promise<Microbit | null> {
    const result = await this.service.microbit({
      where: params,
      select: {
        createdAt: true,
        feedback: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        forgetCount: true,
        highlightedText: true,
        id: true,
        reviewCount: true,
        text: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Microbit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMicrobit(
    @common.Param() params: MicrobitWhereUniqueInput,
    @common.Body() data: MicrobitUpdateInput
  ): Promise<Microbit | null> {
    try {
      return await this.service.updateMicrobit({
        where: params,
        data: {
          ...data,

          flashcard: data.flashcard
            ? {
                connect: data.flashcard,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          feedback: true,

          flashcard: {
            select: {
              id: true,
            },
          },

          forgetCount: true,
          highlightedText: true,
          id: true,
          reviewCount: true,
          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Microbit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMicrobit(
    @common.Param() params: MicrobitWhereUniqueInput
  ): Promise<Microbit | null> {
    try {
      return await this.service.deleteMicrobit({
        where: params,
        select: {
          createdAt: true,
          feedback: true,

          flashcard: {
            select: {
              id: true,
            },
          },

          forgetCount: true,
          highlightedText: true,
          id: true,
          reviewCount: true,
          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
