/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CourseService } from "../course.service";
import { CourseCreateInput } from "./CourseCreateInput";
import { Course } from "./Course";
import { CourseFindManyArgs } from "./CourseFindManyArgs";
import { CourseWhereUniqueInput } from "./CourseWhereUniqueInput";
import { CourseUpdateInput } from "./CourseUpdateInput";
import { CourseSectionFindManyArgs } from "../../courseSection/base/CourseSectionFindManyArgs";
import { CourseSection } from "../../courseSection/base/CourseSection";
import { CourseSectionWhereUniqueInput } from "../../courseSection/base/CourseSectionWhereUniqueInput";
import { FlashcardDeckFindManyArgs } from "../../flashcardDeck/base/FlashcardDeckFindManyArgs";
import { FlashcardDeck } from "../../flashcardDeck/base/FlashcardDeck";
import { FlashcardDeckWhereUniqueInput } from "../../flashcardDeck/base/FlashcardDeckWhereUniqueInput";

export class CourseControllerBase {
  constructor(protected readonly service: CourseService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Course })
  async createCourse(@common.Body() data: CourseCreateInput): Promise<Course> {
    return await this.service.createCourse({
      data: data,
      select: {
        coverImages: true,
        coverVideo: true,
        createdAt: true,
        description: true,
        highlights: true,
        id: true,
        showEnrollmentStats: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Course] })
  @ApiNestedQuery(CourseFindManyArgs)
  async courses(@common.Req() request: Request): Promise<Course[]> {
    const args = plainToClass(CourseFindManyArgs, request.query);
    return this.service.courses({
      ...args,
      select: {
        coverImages: true,
        coverVideo: true,
        createdAt: true,
        description: true,
        highlights: true,
        id: true,
        showEnrollmentStats: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Course })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async course(
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<Course | null> {
    const result = await this.service.course({
      where: params,
      select: {
        coverImages: true,
        coverVideo: true,
        createdAt: true,
        description: true,
        highlights: true,
        id: true,
        showEnrollmentStats: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Course })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCourse(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() data: CourseUpdateInput
  ): Promise<Course | null> {
    try {
      return await this.service.updateCourse({
        where: params,
        data: data,
        select: {
          coverImages: true,
          coverVideo: true,
          createdAt: true,
          description: true,
          highlights: true,
          id: true,
          showEnrollmentStats: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Course })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCourse(
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<Course | null> {
    try {
      return await this.service.deleteCourse({
        where: params,
        select: {
          coverImages: true,
          coverVideo: true,
          createdAt: true,
          description: true,
          highlights: true,
          id: true,
          showEnrollmentStats: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/courseSections")
  @ApiNestedQuery(CourseSectionFindManyArgs)
  async findCourseSections(
    @common.Req() request: Request,
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<CourseSection[]> {
    const query = plainToClass(CourseSectionFindManyArgs, request.query);
    const results = await this.service.findCourseSections(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        icon: true,
        id: true,
        order: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/courseSections")
  async connectCourseSections(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: CourseSectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseSections: {
        connect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/courseSections")
  async updateCourseSections(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: CourseSectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseSections: {
        set: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/courseSections")
  async disconnectCourseSections(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: CourseSectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courseSections: {
        disconnect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/flashcardDecks")
  @ApiNestedQuery(FlashcardDeckFindManyArgs)
  async findFlashcardDecks(
    @common.Req() request: Request,
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<FlashcardDeck[]> {
    const query = plainToClass(FlashcardDeckFindManyArgs, request.query);
    const results = await this.service.findFlashcardDecks(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        courseSubSection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        isSample: true,
        lastUpdated: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/flashcardDecks")
  async connectFlashcardDecks(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: FlashcardDeckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardDecks: {
        connect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/flashcardDecks")
  async updateFlashcardDecks(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: FlashcardDeckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardDecks: {
        set: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/flashcardDecks")
  async disconnectFlashcardDecks(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: FlashcardDeckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardDecks: {
        disconnect: body,
      },
    };
    await this.service.updateCourse({
      where: params,
      data,
      select: { id: true },
    });
  }
}
