/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TimetableEntryService } from "../timetableEntry.service";
import { TimetableEntryCreateInput } from "./TimetableEntryCreateInput";
import { TimetableEntry } from "./TimetableEntry";
import { TimetableEntryFindManyArgs } from "./TimetableEntryFindManyArgs";
import { TimetableEntryWhereUniqueInput } from "./TimetableEntryWhereUniqueInput";
import { TimetableEntryUpdateInput } from "./TimetableEntryUpdateInput";

export class TimetableEntryControllerBase {
  constructor(protected readonly service: TimetableEntryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TimetableEntry })
  async createTimetableEntry(
    @common.Body() data: TimetableEntryCreateInput
  ): Promise<TimetableEntry> {
    return await this.service.createTimetableEntry({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TimetableEntry] })
  @ApiNestedQuery(TimetableEntryFindManyArgs)
  async timetableEntries(
    @common.Req() request: Request
  ): Promise<TimetableEntry[]> {
    const args = plainToClass(TimetableEntryFindManyArgs, request.query);
    return this.service.timetableEntries({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TimetableEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async timetableEntry(
    @common.Param() params: TimetableEntryWhereUniqueInput
  ): Promise<TimetableEntry | null> {
    const result = await this.service.timetableEntry({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TimetableEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTimetableEntry(
    @common.Param() params: TimetableEntryWhereUniqueInput,
    @common.Body() data: TimetableEntryUpdateInput
  ): Promise<TimetableEntry | null> {
    try {
      return await this.service.updateTimetableEntry({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TimetableEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTimetableEntry(
    @common.Param() params: TimetableEntryWhereUniqueInput
  ): Promise<TimetableEntry | null> {
    try {
      return await this.service.deleteTimetableEntry({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
