/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, TimetableEntry as PrismaTimetableEntry } from "@prisma/client";

export class TimetableEntryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TimetableEntryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.timetableEntry.count(args);
  }

  async timetableEntries(
    args: Prisma.TimetableEntryFindManyArgs
  ): Promise<PrismaTimetableEntry[]> {
    return this.prisma.timetableEntry.findMany(args);
  }
  async timetableEntry(
    args: Prisma.TimetableEntryFindUniqueArgs
  ): Promise<PrismaTimetableEntry | null> {
    return this.prisma.timetableEntry.findUnique(args);
  }
  async createTimetableEntry(
    args: Prisma.TimetableEntryCreateArgs
  ): Promise<PrismaTimetableEntry> {
    return this.prisma.timetableEntry.create(args);
  }
  async updateTimetableEntry(
    args: Prisma.TimetableEntryUpdateArgs
  ): Promise<PrismaTimetableEntry> {
    return this.prisma.timetableEntry.update(args);
  }
  async deleteTimetableEntry(
    args: Prisma.TimetableEntryDeleteArgs
  ): Promise<PrismaTimetableEntry> {
    return this.prisma.timetableEntry.delete(args);
  }
}
