/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TimetableEntry } from "./TimetableEntry";
import { TimetableEntryCountArgs } from "./TimetableEntryCountArgs";
import { TimetableEntryFindManyArgs } from "./TimetableEntryFindManyArgs";
import { TimetableEntryFindUniqueArgs } from "./TimetableEntryFindUniqueArgs";
import { DeleteTimetableEntryArgs } from "./DeleteTimetableEntryArgs";
import { TimetableEntryService } from "../timetableEntry.service";
@graphql.Resolver(() => TimetableEntry)
export class TimetableEntryResolverBase {
  constructor(protected readonly service: TimetableEntryService) {}

  async _timetableEntriesMeta(
    @graphql.Args() args: TimetableEntryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TimetableEntry])
  async timetableEntries(
    @graphql.Args() args: TimetableEntryFindManyArgs
  ): Promise<TimetableEntry[]> {
    return this.service.timetableEntries(args);
  }

  @graphql.Query(() => TimetableEntry, { nullable: true })
  async timetableEntry(
    @graphql.Args() args: TimetableEntryFindUniqueArgs
  ): Promise<TimetableEntry | null> {
    const result = await this.service.timetableEntry(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TimetableEntry)
  async deleteTimetableEntry(
    @graphql.Args() args: DeleteTimetableEntryArgs
  ): Promise<TimetableEntry | null> {
    try {
      return await this.service.deleteTimetableEntry(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
