/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FlashcardDeck } from "./FlashcardDeck";
import { FlashcardDeckCountArgs } from "./FlashcardDeckCountArgs";
import { FlashcardDeckFindManyArgs } from "./FlashcardDeckFindManyArgs";
import { FlashcardDeckFindUniqueArgs } from "./FlashcardDeckFindUniqueArgs";
import { CreateFlashcardDeckArgs } from "./CreateFlashcardDeckArgs";
import { UpdateFlashcardDeckArgs } from "./UpdateFlashcardDeckArgs";
import { DeleteFlashcardDeckArgs } from "./DeleteFlashcardDeckArgs";
import { ErrorCardFindManyArgs } from "../../errorCard/base/ErrorCardFindManyArgs";
import { ErrorCard } from "../../errorCard/base/ErrorCard";
import { FlashcardSessionFindManyArgs } from "../../flashcardSession/base/FlashcardSessionFindManyArgs";
import { FlashcardSession } from "../../flashcardSession/base/FlashcardSession";
import { FlashcardFindManyArgs } from "../../flashcard/base/FlashcardFindManyArgs";
import { Flashcard } from "../../flashcard/base/Flashcard";
import { Course } from "../../course/base/Course";
import { FlashcardDeckService } from "../flashcardDeck.service";
@graphql.Resolver(() => FlashcardDeck)
export class FlashcardDeckResolverBase {
  constructor(protected readonly service: FlashcardDeckService) {}

  async _flashcardDecksMeta(
    @graphql.Args() args: FlashcardDeckCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FlashcardDeck])
  async flashcardDecks(
    @graphql.Args() args: FlashcardDeckFindManyArgs
  ): Promise<FlashcardDeck[]> {
    return this.service.flashcardDecks(args);
  }

  @graphql.Query(() => FlashcardDeck, { nullable: true })
  async flashcardDeck(
    @graphql.Args() args: FlashcardDeckFindUniqueArgs
  ): Promise<FlashcardDeck | null> {
    const result = await this.service.flashcardDeck(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FlashcardDeck)
  async createFlashcardDeck(
    @graphql.Args() args: CreateFlashcardDeckArgs
  ): Promise<FlashcardDeck> {
    return await this.service.createFlashcardDeck({
      ...args,
      data: {
        ...args.data,

        course: args.data.course
          ? {
              connect: args.data.course,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => FlashcardDeck)
  async updateFlashcardDeck(
    @graphql.Args() args: UpdateFlashcardDeckArgs
  ): Promise<FlashcardDeck | null> {
    try {
      return await this.service.updateFlashcardDeck({
        ...args,
        data: {
          ...args.data,

          course: args.data.course
            ? {
                connect: args.data.course,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FlashcardDeck)
  async deleteFlashcardDeck(
    @graphql.Args() args: DeleteFlashcardDeckArgs
  ): Promise<FlashcardDeck | null> {
    try {
      return await this.service.deleteFlashcardDeck(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [ErrorCard], { name: "errorCards" })
  async findErrorCards(
    @graphql.Parent() parent: FlashcardDeck,
    @graphql.Args() args: ErrorCardFindManyArgs
  ): Promise<ErrorCard[]> {
    const results = await this.service.findErrorCards(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [FlashcardSession], { name: "flashcardSessions" })
  async findFlashcardSessions(
    @graphql.Parent() parent: FlashcardDeck,
    @graphql.Args() args: FlashcardSessionFindManyArgs
  ): Promise<FlashcardSession[]> {
    const results = await this.service.findFlashcardSessions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Flashcard], { name: "flashcards" })
  async findFlashcards(
    @graphql.Parent() parent: FlashcardDeck,
    @graphql.Args() args: FlashcardFindManyArgs
  ): Promise<Flashcard[]> {
    const results = await this.service.findFlashcards(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Course, {
    nullable: true,
    name: "course",
  })
  async getCourse(
    @graphql.Parent() parent: FlashcardDeck
  ): Promise<Course | null> {
    const result = await this.service.getCourse(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
