/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CourseWhereUniqueInput } from "../../course/base/CourseWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { ErrorCardUpdateManyWithoutFlashcardDecksInput } from "./ErrorCardUpdateManyWithoutFlashcardDecksInput";
import { FlashcardUpdateManyWithoutFlashcardDecksInput } from "./FlashcardUpdateManyWithoutFlashcardDecksInput";

@InputType()
class FlashcardDeckUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CourseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CourseWhereUniqueInput)
  @IsOptional()
  @Field(() => CourseWhereUniqueInput, {
    nullable: true,
  })
  course?: CourseWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ErrorCardUpdateManyWithoutFlashcardDecksInput,
  })
  @ValidateNested()
  @Type(() => ErrorCardUpdateManyWithoutFlashcardDecksInput)
  @IsOptional()
  @Field(() => ErrorCardUpdateManyWithoutFlashcardDecksInput, {
    nullable: true,
  })
  errorCards?: ErrorCardUpdateManyWithoutFlashcardDecksInput;

  @ApiProperty({
    required: false,
    type: () => FlashcardUpdateManyWithoutFlashcardDecksInput,
  })
  @ValidateNested()
  @Type(() => FlashcardUpdateManyWithoutFlashcardDecksInput)
  @IsOptional()
  @Field(() => FlashcardUpdateManyWithoutFlashcardDecksInput, {
    nullable: true,
  })
  flashcards?: FlashcardUpdateManyWithoutFlashcardDecksInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  lastUpdated?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tags?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { FlashcardDeckUpdateInput as FlashcardDeckUpdateInput };
