/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FlashcardDeckService } from "../flashcardDeck.service";
import { FlashcardDeckCreateInput } from "./FlashcardDeckCreateInput";
import { FlashcardDeck } from "./FlashcardDeck";
import { FlashcardDeckFindManyArgs } from "./FlashcardDeckFindManyArgs";
import { FlashcardDeckWhereUniqueInput } from "./FlashcardDeckWhereUniqueInput";
import { FlashcardDeckUpdateInput } from "./FlashcardDeckUpdateInput";
import { ErrorCardFindManyArgs } from "../../errorCard/base/ErrorCardFindManyArgs";
import { ErrorCard } from "../../errorCard/base/ErrorCard";
import { ErrorCardWhereUniqueInput } from "../../errorCard/base/ErrorCardWhereUniqueInput";
import { FlashcardSessionFindManyArgs } from "../../flashcardSession/base/FlashcardSessionFindManyArgs";
import { FlashcardSession } from "../../flashcardSession/base/FlashcardSession";
import { FlashcardSessionWhereUniqueInput } from "../../flashcardSession/base/FlashcardSessionWhereUniqueInput";
import { FlashcardFindManyArgs } from "../../flashcard/base/FlashcardFindManyArgs";
import { Flashcard } from "../../flashcard/base/Flashcard";
import { FlashcardWhereUniqueInput } from "../../flashcard/base/FlashcardWhereUniqueInput";

export class FlashcardDeckControllerBase {
  constructor(protected readonly service: FlashcardDeckService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FlashcardDeck })
  async createFlashcardDeck(
    @common.Body() data: FlashcardDeckCreateInput
  ): Promise<FlashcardDeck> {
    return await this.service.createFlashcardDeck({
      data: {
        ...data,

        course: data.course
          ? {
              connect: data.course,
            }
          : undefined,

        courseSubSection: data.courseSubSection
          ? {
              connect: data.courseSubSection,
            }
          : undefined,
      },
      select: {
        course: {
          select: {
            id: true,
          },
        },

        courseSubSection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        isSample: true,
        lastUpdated: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FlashcardDeck] })
  @ApiNestedQuery(FlashcardDeckFindManyArgs)
  async flashcardDecks(
    @common.Req() request: Request
  ): Promise<FlashcardDeck[]> {
    const args = plainToClass(FlashcardDeckFindManyArgs, request.query);
    return this.service.flashcardDecks({
      ...args,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        courseSubSection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        isSample: true,
        lastUpdated: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FlashcardDeck })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async flashcardDeck(
    @common.Param() params: FlashcardDeckWhereUniqueInput
  ): Promise<FlashcardDeck | null> {
    const result = await this.service.flashcardDeck({
      where: params,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        courseSubSection: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        isSample: true,
        lastUpdated: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FlashcardDeck })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFlashcardDeck(
    @common.Param() params: FlashcardDeckWhereUniqueInput,
    @common.Body() data: FlashcardDeckUpdateInput
  ): Promise<FlashcardDeck | null> {
    try {
      return await this.service.updateFlashcardDeck({
        where: params,
        data: {
          ...data,

          course: data.course
            ? {
                connect: data.course,
              }
            : undefined,

          courseSubSection: data.courseSubSection
            ? {
                connect: data.courseSubSection,
              }
            : undefined,
        },
        select: {
          course: {
            select: {
              id: true,
            },
          },

          courseSubSection: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          isSample: true,
          lastUpdated: true,
          tags: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FlashcardDeck })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFlashcardDeck(
    @common.Param() params: FlashcardDeckWhereUniqueInput
  ): Promise<FlashcardDeck | null> {
    try {
      return await this.service.deleteFlashcardDeck({
        where: params,
        select: {
          course: {
            select: {
              id: true,
            },
          },

          courseSubSection: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          isSample: true,
          lastUpdated: true,
          tags: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/errorCards")
  @ApiNestedQuery(ErrorCardFindManyArgs)
  async findErrorCards(
    @common.Req() request: Request,
    @common.Param() params: FlashcardDeckWhereUniqueInput
  ): Promise<ErrorCard[]> {
    const query = plainToClass(ErrorCardFindManyArgs, request.query);
    const results = await this.service.findErrorCards(params.id, {
      ...query,
      select: {
        createdAt: true,
        errorCount: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        id: true,

        studentProfile: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/errorCards")
  async connectErrorCards(
    @common.Param() params: FlashcardDeckWhereUniqueInput,
    @common.Body() body: ErrorCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      errorCards: {
        connect: body,
      },
    };
    await this.service.updateFlashcardDeck({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/errorCards")
  async updateErrorCards(
    @common.Param() params: FlashcardDeckWhereUniqueInput,
    @common.Body() body: ErrorCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      errorCards: {
        set: body,
      },
    };
    await this.service.updateFlashcardDeck({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/errorCards")
  async disconnectErrorCards(
    @common.Param() params: FlashcardDeckWhereUniqueInput,
    @common.Body() body: ErrorCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      errorCards: {
        disconnect: body,
      },
    };
    await this.service.updateFlashcardDeck({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/flashcardSessions")
  @ApiNestedQuery(FlashcardSessionFindManyArgs)
  async findFlashcardSessions(
    @common.Req() request: Request,
    @common.Param() params: FlashcardDeckWhereUniqueInput
  ): Promise<FlashcardSession[]> {
    const query = plainToClass(FlashcardSessionFindManyArgs, request.query);
    const results = await this.service.findFlashcardSessions(params.id, {
      ...query,
      select: {
        completed: true,
        createdAt: true,
        endTime: true,

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        id: true,
        progress: true,
        sessionType: true,
        shuffleMode: true,
        startTime: true,

        studentProfile: {
          select: {
            id: true,
          },
        },

        summaryStats: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/flashcardSessions")
  async connectFlashcardSessions(
    @common.Param() params: FlashcardDeckWhereUniqueInput,
    @common.Body() body: FlashcardSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardSessions: {
        connect: body,
      },
    };
    await this.service.updateFlashcardDeck({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/flashcardSessions")
  async updateFlashcardSessions(
    @common.Param() params: FlashcardDeckWhereUniqueInput,
    @common.Body() body: FlashcardSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardSessions: {
        set: body,
      },
    };
    await this.service.updateFlashcardDeck({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/flashcardSessions")
  async disconnectFlashcardSessions(
    @common.Param() params: FlashcardDeckWhereUniqueInput,
    @common.Body() body: FlashcardSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardSessions: {
        disconnect: body,
      },
    };
    await this.service.updateFlashcardDeck({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/flashcards")
  @ApiNestedQuery(FlashcardFindManyArgs)
  async findFlashcards(
    @common.Req() request: Request,
    @common.Param() params: FlashcardDeckWhereUniqueInput
  ): Promise<Flashcard[]> {
    const query = plainToClass(FlashcardFindManyArgs, request.query);
    const results = await this.service.findFlashcards(params.id, {
      ...query,
      select: {
        backContent: true,
        cardType: true,
        correctOption: true,
        createdAt: true,

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        frontContent: true,
        hint: true,
        id: true,
        options: true,
        tags: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/flashcards")
  async connectFlashcards(
    @common.Param() params: FlashcardDeckWhereUniqueInput,
    @common.Body() body: FlashcardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcards: {
        connect: body,
      },
    };
    await this.service.updateFlashcardDeck({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/flashcards")
  async updateFlashcards(
    @common.Param() params: FlashcardDeckWhereUniqueInput,
    @common.Body() body: FlashcardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcards: {
        set: body,
      },
    };
    await this.service.updateFlashcardDeck({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/flashcards")
  async disconnectFlashcards(
    @common.Param() params: FlashcardDeckWhereUniqueInput,
    @common.Body() body: FlashcardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcards: {
        disconnect: body,
      },
    };
    await this.service.updateFlashcardDeck({
      where: params,
      data,
      select: { id: true },
    });
  }
}
