/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CourseWhereUniqueInput } from "../../course/base/CourseWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { CourseSubSectionWhereUniqueInput } from "../../courseSubSection/base/CourseSubSectionWhereUniqueInput";
import { ErrorCardCreateNestedManyWithoutFlashcardDecksInput } from "./ErrorCardCreateNestedManyWithoutFlashcardDecksInput";
import { FlashcardSessionCreateNestedManyWithoutFlashcardDecksInput } from "./FlashcardSessionCreateNestedManyWithoutFlashcardDecksInput";
import { FlashcardCreateNestedManyWithoutFlashcardDecksInput } from "./FlashcardCreateNestedManyWithoutFlashcardDecksInput";

@InputType()
class FlashcardDeckCreateInput {
  @ApiProperty({
    required: false,
    type: () => CourseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CourseWhereUniqueInput)
  @IsOptional()
  @Field(() => CourseWhereUniqueInput, {
    nullable: true,
  })
  course?: CourseWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CourseSubSectionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CourseSubSectionWhereUniqueInput)
  @IsOptional()
  @Field(() => CourseSubSectionWhereUniqueInput, {
    nullable: true,
  })
  courseSubSection?: CourseSubSectionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ErrorCardCreateNestedManyWithoutFlashcardDecksInput,
  })
  @ValidateNested()
  @Type(() => ErrorCardCreateNestedManyWithoutFlashcardDecksInput)
  @IsOptional()
  @Field(() => ErrorCardCreateNestedManyWithoutFlashcardDecksInput, {
    nullable: true,
  })
  errorCards?: ErrorCardCreateNestedManyWithoutFlashcardDecksInput;

  @ApiProperty({
    required: false,
    type: () => FlashcardSessionCreateNestedManyWithoutFlashcardDecksInput,
  })
  @ValidateNested()
  @Type(() => FlashcardSessionCreateNestedManyWithoutFlashcardDecksInput)
  @IsOptional()
  @Field(() => FlashcardSessionCreateNestedManyWithoutFlashcardDecksInput, {
    nullable: true,
  })
  flashcardSessions?: FlashcardSessionCreateNestedManyWithoutFlashcardDecksInput;

  @ApiProperty({
    required: false,
    type: () => FlashcardCreateNestedManyWithoutFlashcardDecksInput,
  })
  @ValidateNested()
  @Type(() => FlashcardCreateNestedManyWithoutFlashcardDecksInput)
  @IsOptional()
  @Field(() => FlashcardCreateNestedManyWithoutFlashcardDecksInput, {
    nullable: true,
  })
  flashcards?: FlashcardCreateNestedManyWithoutFlashcardDecksInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isSample?: boolean | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  lastUpdated?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tags?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { FlashcardDeckCreateInput as FlashcardDeckCreateInput };
