/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  FlashcardDeck as PrismaFlashcardDeck,
  ErrorCard as PrismaErrorCard,
  FlashcardSession as PrismaFlashcardSession,
  Flashcard as PrismaFlashcard,
  Course as PrismaCourse,
} from "@prisma/client";

export class FlashcardDeckServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FlashcardDeckCountArgs, "select">
  ): Promise<number> {
    return this.prisma.flashcardDeck.count(args);
  }

  async flashcardDecks(
    args: Prisma.FlashcardDeckFindManyArgs
  ): Promise<PrismaFlashcardDeck[]> {
    return this.prisma.flashcardDeck.findMany(args);
  }
  async flashcardDeck(
    args: Prisma.FlashcardDeckFindUniqueArgs
  ): Promise<PrismaFlashcardDeck | null> {
    return this.prisma.flashcardDeck.findUnique(args);
  }
  async createFlashcardDeck(
    args: Prisma.FlashcardDeckCreateArgs
  ): Promise<PrismaFlashcardDeck> {
    return this.prisma.flashcardDeck.create(args);
  }
  async updateFlashcardDeck(
    args: Prisma.FlashcardDeckUpdateArgs
  ): Promise<PrismaFlashcardDeck> {
    return this.prisma.flashcardDeck.update(args);
  }
  async deleteFlashcardDeck(
    args: Prisma.FlashcardDeckDeleteArgs
  ): Promise<PrismaFlashcardDeck> {
    return this.prisma.flashcardDeck.delete(args);
  }

  async findErrorCards(
    parentId: string,
    args: Prisma.ErrorCardFindManyArgs
  ): Promise<PrismaErrorCard[]> {
    return this.prisma.flashcardDeck
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .errorCards(args);
  }

  async findFlashcardSessions(
    parentId: string,
    args: Prisma.FlashcardSessionFindManyArgs
  ): Promise<PrismaFlashcardSession[]> {
    return this.prisma.flashcardDeck
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .flashcardSessions(args);
  }

  async findFlashcards(
    parentId: string,
    args: Prisma.FlashcardFindManyArgs
  ): Promise<PrismaFlashcard[]> {
    return this.prisma.flashcardDeck
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .flashcards(args);
  }

  async getCourse(parentId: string): Promise<PrismaCourse | null> {
    return this.prisma.flashcardDeck
      .findUnique({
        where: { id: parentId },
      })
      .course();
  }
}
