/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CourseWhereUniqueInput } from "../../course/base/CourseWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CourseSubSectionWhereUniqueInput } from "../../courseSubSection/base/CourseSubSectionWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ErrorCardListRelationFilter } from "../../errorCard/base/ErrorCardListRelationFilter";
import { FlashcardSessionListRelationFilter } from "../../flashcardSession/base/FlashcardSessionListRelationFilter";
import { FlashcardListRelationFilter } from "../../flashcard/base/FlashcardListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";

@InputType()
class FlashcardDeckWhereInput {
  @ApiProperty({
    required: false,
    type: () => CourseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CourseWhereUniqueInput)
  @IsOptional()
  @Field(() => CourseWhereUniqueInput, {
    nullable: true,
  })
  course?: CourseWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => CourseSubSectionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CourseSubSectionWhereUniqueInput)
  @IsOptional()
  @Field(() => CourseSubSectionWhereUniqueInput, {
    nullable: true,
  })
  courseSubSection?: CourseSubSectionWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ErrorCardListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ErrorCardListRelationFilter)
  @IsOptional()
  @Field(() => ErrorCardListRelationFilter, {
    nullable: true,
  })
  errorCards?: ErrorCardListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FlashcardSessionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FlashcardSessionListRelationFilter)
  @IsOptional()
  @Field(() => FlashcardSessionListRelationFilter, {
    nullable: true,
  })
  flashcardSessions?: FlashcardSessionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FlashcardListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FlashcardListRelationFilter)
  @IsOptional()
  @Field(() => FlashcardListRelationFilter, {
    nullable: true,
  })
  flashcards?: FlashcardListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isSample?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  lastUpdated?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  tags?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;
}

export { FlashcardDeckWhereInput as FlashcardDeckWhereInput };
