/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WalletTransactionService } from "../walletTransaction.service";
import { WalletTransactionCreateInput } from "./WalletTransactionCreateInput";
import { WalletTransaction } from "./WalletTransaction";
import { WalletTransactionFindManyArgs } from "./WalletTransactionFindManyArgs";
import { WalletTransactionWhereUniqueInput } from "./WalletTransactionWhereUniqueInput";
import { WalletTransactionUpdateInput } from "./WalletTransactionUpdateInput";

export class WalletTransactionControllerBase {
  constructor(protected readonly service: WalletTransactionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WalletTransaction })
  async createWalletTransaction(
    @common.Body() data: WalletTransactionCreateInput
  ): Promise<WalletTransaction> {
    return await this.service.createWalletTransaction({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [WalletTransaction] })
  @ApiNestedQuery(WalletTransactionFindManyArgs)
  async walletTransactions(
    @common.Req() request: Request
  ): Promise<WalletTransaction[]> {
    const args = plainToClass(WalletTransactionFindManyArgs, request.query);
    return this.service.walletTransactions({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WalletTransaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async walletTransaction(
    @common.Param() params: WalletTransactionWhereUniqueInput
  ): Promise<WalletTransaction | null> {
    const result = await this.service.walletTransaction({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WalletTransaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateWalletTransaction(
    @common.Param() params: WalletTransactionWhereUniqueInput,
    @common.Body() data: WalletTransactionUpdateInput
  ): Promise<WalletTransaction | null> {
    try {
      return await this.service.updateWalletTransaction({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WalletTransaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteWalletTransaction(
    @common.Param() params: WalletTransactionWhereUniqueInput
  ): Promise<WalletTransaction | null> {
    try {
      return await this.service.deleteWalletTransaction({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
