/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { WalletTransaction } from "./WalletTransaction";
import { WalletTransactionCountArgs } from "./WalletTransactionCountArgs";
import { WalletTransactionFindManyArgs } from "./WalletTransactionFindManyArgs";
import { WalletTransactionFindUniqueArgs } from "./WalletTransactionFindUniqueArgs";
import { DeleteWalletTransactionArgs } from "./DeleteWalletTransactionArgs";
import { WalletTransactionService } from "../walletTransaction.service";
@graphql.Resolver(() => WalletTransaction)
export class WalletTransactionResolverBase {
  constructor(protected readonly service: WalletTransactionService) {}

  async _walletTransactionsMeta(
    @graphql.Args() args: WalletTransactionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [WalletTransaction])
  async walletTransactions(
    @graphql.Args() args: WalletTransactionFindManyArgs
  ): Promise<WalletTransaction[]> {
    return this.service.walletTransactions(args);
  }

  @graphql.Query(() => WalletTransaction, { nullable: true })
  async walletTransaction(
    @graphql.Args() args: WalletTransactionFindUniqueArgs
  ): Promise<WalletTransaction | null> {
    const result = await this.service.walletTransaction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => WalletTransaction)
  async deleteWalletTransaction(
    @graphql.Args() args: DeleteWalletTransactionArgs
  ): Promise<WalletTransaction | null> {
    try {
      return await this.service.deleteWalletTransaction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
