/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  WalletTransaction as PrismaWalletTransaction,
} from "@prisma/client";

export class WalletTransactionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.WalletTransactionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.walletTransaction.count(args);
  }

  async walletTransactions(
    args: Prisma.WalletTransactionFindManyArgs
  ): Promise<PrismaWalletTransaction[]> {
    return this.prisma.walletTransaction.findMany(args);
  }
  async walletTransaction(
    args: Prisma.WalletTransactionFindUniqueArgs
  ): Promise<PrismaWalletTransaction | null> {
    return this.prisma.walletTransaction.findUnique(args);
  }
  async createWalletTransaction(
    args: Prisma.WalletTransactionCreateArgs
  ): Promise<PrismaWalletTransaction> {
    return this.prisma.walletTransaction.create(args);
  }
  async updateWalletTransaction(
    args: Prisma.WalletTransactionUpdateArgs
  ): Promise<PrismaWalletTransaction> {
    return this.prisma.walletTransaction.update(args);
  }
  async deleteWalletTransaction(
    args: Prisma.WalletTransactionDeleteArgs
  ): Promise<PrismaWalletTransaction> {
    return this.prisma.walletTransaction.delete(args);
  }
}
