/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Flashcard as PrismaFlashcard,
  ErrorCard as PrismaErrorCard,
  Microbit as PrismaMicrobit,
  FlashcardDeck as PrismaFlashcardDeck,
} from "@prisma/client";

export class FlashcardServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FlashcardCountArgs, "select">
  ): Promise<number> {
    return this.prisma.flashcard.count(args);
  }

  async flashcards(
    args: Prisma.FlashcardFindManyArgs
  ): Promise<PrismaFlashcard[]> {
    return this.prisma.flashcard.findMany(args);
  }
  async flashcard(
    args: Prisma.FlashcardFindUniqueArgs
  ): Promise<PrismaFlashcard | null> {
    return this.prisma.flashcard.findUnique(args);
  }
  async createFlashcard(
    args: Prisma.FlashcardCreateArgs
  ): Promise<PrismaFlashcard> {
    return this.prisma.flashcard.create(args);
  }
  async updateFlashcard(
    args: Prisma.FlashcardUpdateArgs
  ): Promise<PrismaFlashcard> {
    return this.prisma.flashcard.update(args);
  }
  async deleteFlashcard(
    args: Prisma.FlashcardDeleteArgs
  ): Promise<PrismaFlashcard> {
    return this.prisma.flashcard.delete(args);
  }

  async findErrorCards(
    parentId: string,
    args: Prisma.ErrorCardFindManyArgs
  ): Promise<PrismaErrorCard[]> {
    return this.prisma.flashcard
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .errorCards(args);
  }

  async findMicrobits(
    parentId: string,
    args: Prisma.MicrobitFindManyArgs
  ): Promise<PrismaMicrobit[]> {
    return this.prisma.flashcard
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .microbits(args);
  }

  async getFlashcardDeck(
    parentId: string
  ): Promise<PrismaFlashcardDeck | null> {
    return this.prisma.flashcard
      .findUnique({
        where: { id: parentId },
      })
      .flashcardDeck();
  }
}
