/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Flashcard } from "./Flashcard";
import { FlashcardCountArgs } from "./FlashcardCountArgs";
import { FlashcardFindManyArgs } from "./FlashcardFindManyArgs";
import { FlashcardFindUniqueArgs } from "./FlashcardFindUniqueArgs";
import { CreateFlashcardArgs } from "./CreateFlashcardArgs";
import { UpdateFlashcardArgs } from "./UpdateFlashcardArgs";
import { DeleteFlashcardArgs } from "./DeleteFlashcardArgs";
import { ErrorCardFindManyArgs } from "../../errorCard/base/ErrorCardFindManyArgs";
import { ErrorCard } from "../../errorCard/base/ErrorCard";
import { MicrobitFindManyArgs } from "../../microbit/base/MicrobitFindManyArgs";
import { Microbit } from "../../microbit/base/Microbit";
import { FlashcardDeck } from "../../flashcardDeck/base/FlashcardDeck";
import { FlashcardService } from "../flashcard.service";
@graphql.Resolver(() => Flashcard)
export class FlashcardResolverBase {
  constructor(protected readonly service: FlashcardService) {}

  async _flashcardsMeta(
    @graphql.Args() args: FlashcardCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Flashcard])
  async flashcards(
    @graphql.Args() args: FlashcardFindManyArgs
  ): Promise<Flashcard[]> {
    return this.service.flashcards(args);
  }

  @graphql.Query(() => Flashcard, { nullable: true })
  async flashcard(
    @graphql.Args() args: FlashcardFindUniqueArgs
  ): Promise<Flashcard | null> {
    const result = await this.service.flashcard(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Flashcard)
  async createFlashcard(
    @graphql.Args() args: CreateFlashcardArgs
  ): Promise<Flashcard> {
    return await this.service.createFlashcard({
      ...args,
      data: {
        ...args.data,

        flashcardDeck: args.data.flashcardDeck
          ? {
              connect: args.data.flashcardDeck,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Flashcard)
  async updateFlashcard(
    @graphql.Args() args: UpdateFlashcardArgs
  ): Promise<Flashcard | null> {
    try {
      return await this.service.updateFlashcard({
        ...args,
        data: {
          ...args.data,

          flashcardDeck: args.data.flashcardDeck
            ? {
                connect: args.data.flashcardDeck,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Flashcard)
  async deleteFlashcard(
    @graphql.Args() args: DeleteFlashcardArgs
  ): Promise<Flashcard | null> {
    try {
      return await this.service.deleteFlashcard(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [ErrorCard], { name: "errorCards" })
  async findErrorCards(
    @graphql.Parent() parent: Flashcard,
    @graphql.Args() args: ErrorCardFindManyArgs
  ): Promise<ErrorCard[]> {
    const results = await this.service.findErrorCards(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Microbit], { name: "microbits" })
  async findMicrobits(
    @graphql.Parent() parent: Flashcard,
    @graphql.Args() args: MicrobitFindManyArgs
  ): Promise<Microbit[]> {
    const results = await this.service.findMicrobits(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => FlashcardDeck, {
    nullable: true,
    name: "flashcardDeck",
  })
  async getFlashcardDeck(
    @graphql.Parent() parent: Flashcard
  ): Promise<FlashcardDeck | null> {
    const result = await this.service.getFlashcardDeck(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
