/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ErrorCardCreateNestedManyWithoutFlashcardsInput } from "./ErrorCardCreateNestedManyWithoutFlashcardsInput";
import { Type } from "class-transformer";
import { FlashcardDeckWhereUniqueInput } from "../../flashcardDeck/base/FlashcardDeckWhereUniqueInput";
import { FlashcardSessionEntryCreateNestedManyWithoutFlashcardsInput } from "./FlashcardSessionEntryCreateNestedManyWithoutFlashcardsInput";
import { MicrobitCreateNestedManyWithoutFlashcardsInput } from "./MicrobitCreateNestedManyWithoutFlashcardsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class FlashcardCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  backContent?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  cardType?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  correctOption?: string | null;

  @ApiProperty({
    required: false,
    type: () => ErrorCardCreateNestedManyWithoutFlashcardsInput,
  })
  @ValidateNested()
  @Type(() => ErrorCardCreateNestedManyWithoutFlashcardsInput)
  @IsOptional()
  @Field(() => ErrorCardCreateNestedManyWithoutFlashcardsInput, {
    nullable: true,
  })
  errorCards?: ErrorCardCreateNestedManyWithoutFlashcardsInput;

  @ApiProperty({
    required: false,
    type: () => FlashcardDeckWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FlashcardDeckWhereUniqueInput)
  @IsOptional()
  @Field(() => FlashcardDeckWhereUniqueInput, {
    nullable: true,
  })
  flashcardDeck?: FlashcardDeckWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => FlashcardSessionEntryCreateNestedManyWithoutFlashcardsInput,
  })
  @ValidateNested()
  @Type(() => FlashcardSessionEntryCreateNestedManyWithoutFlashcardsInput)
  @IsOptional()
  @Field(() => FlashcardSessionEntryCreateNestedManyWithoutFlashcardsInput, {
    nullable: true,
  })
  flashcardSessionEntries?: FlashcardSessionEntryCreateNestedManyWithoutFlashcardsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  frontContent?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  hint?: string | null;

  @ApiProperty({
    required: false,
    type: () => MicrobitCreateNestedManyWithoutFlashcardsInput,
  })
  @ValidateNested()
  @Type(() => MicrobitCreateNestedManyWithoutFlashcardsInput)
  @IsOptional()
  @Field(() => MicrobitCreateNestedManyWithoutFlashcardsInput, {
    nullable: true,
  })
  microbits?: MicrobitCreateNestedManyWithoutFlashcardsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  options?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tags?: string | null;
}

export { FlashcardCreateInput as FlashcardCreateInput };
