/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FlashcardService } from "../flashcard.service";
import { FlashcardCreateInput } from "./FlashcardCreateInput";
import { Flashcard } from "./Flashcard";
import { FlashcardFindManyArgs } from "./FlashcardFindManyArgs";
import { FlashcardWhereUniqueInput } from "./FlashcardWhereUniqueInput";
import { FlashcardUpdateInput } from "./FlashcardUpdateInput";
import { ErrorCardFindManyArgs } from "../../errorCard/base/ErrorCardFindManyArgs";
import { ErrorCard } from "../../errorCard/base/ErrorCard";
import { ErrorCardWhereUniqueInput } from "../../errorCard/base/ErrorCardWhereUniqueInput";
import { FlashcardSessionEntryFindManyArgs } from "../../flashcardSessionEntry/base/FlashcardSessionEntryFindManyArgs";
import { FlashcardSessionEntry } from "../../flashcardSessionEntry/base/FlashcardSessionEntry";
import { FlashcardSessionEntryWhereUniqueInput } from "../../flashcardSessionEntry/base/FlashcardSessionEntryWhereUniqueInput";
import { MicrobitFindManyArgs } from "../../microbit/base/MicrobitFindManyArgs";
import { Microbit } from "../../microbit/base/Microbit";
import { MicrobitWhereUniqueInput } from "../../microbit/base/MicrobitWhereUniqueInput";

export class FlashcardControllerBase {
  constructor(protected readonly service: FlashcardService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Flashcard })
  async createFlashcard(
    @common.Body() data: FlashcardCreateInput
  ): Promise<Flashcard> {
    return await this.service.createFlashcard({
      data: {
        ...data,

        flashcardDeck: data.flashcardDeck
          ? {
              connect: data.flashcardDeck,
            }
          : undefined,
      },
      select: {
        backContent: true,
        cardType: true,
        correctOption: true,
        createdAt: true,

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        frontContent: true,
        hint: true,
        id: true,
        options: true,
        tags: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Flashcard] })
  @ApiNestedQuery(FlashcardFindManyArgs)
  async flashcards(@common.Req() request: Request): Promise<Flashcard[]> {
    const args = plainToClass(FlashcardFindManyArgs, request.query);
    return this.service.flashcards({
      ...args,
      select: {
        backContent: true,
        cardType: true,
        correctOption: true,
        createdAt: true,

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        frontContent: true,
        hint: true,
        id: true,
        options: true,
        tags: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Flashcard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async flashcard(
    @common.Param() params: FlashcardWhereUniqueInput
  ): Promise<Flashcard | null> {
    const result = await this.service.flashcard({
      where: params,
      select: {
        backContent: true,
        cardType: true,
        correctOption: true,
        createdAt: true,

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        frontContent: true,
        hint: true,
        id: true,
        options: true,
        tags: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Flashcard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFlashcard(
    @common.Param() params: FlashcardWhereUniqueInput,
    @common.Body() data: FlashcardUpdateInput
  ): Promise<Flashcard | null> {
    try {
      return await this.service.updateFlashcard({
        where: params,
        data: {
          ...data,

          flashcardDeck: data.flashcardDeck
            ? {
                connect: data.flashcardDeck,
              }
            : undefined,
        },
        select: {
          backContent: true,
          cardType: true,
          correctOption: true,
          createdAt: true,

          flashcardDeck: {
            select: {
              id: true,
            },
          },

          frontContent: true,
          hint: true,
          id: true,
          options: true,
          tags: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Flashcard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFlashcard(
    @common.Param() params: FlashcardWhereUniqueInput
  ): Promise<Flashcard | null> {
    try {
      return await this.service.deleteFlashcard({
        where: params,
        select: {
          backContent: true,
          cardType: true,
          correctOption: true,
          createdAt: true,

          flashcardDeck: {
            select: {
              id: true,
            },
          },

          frontContent: true,
          hint: true,
          id: true,
          options: true,
          tags: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/errorCards")
  @ApiNestedQuery(ErrorCardFindManyArgs)
  async findErrorCards(
    @common.Req() request: Request,
    @common.Param() params: FlashcardWhereUniqueInput
  ): Promise<ErrorCard[]> {
    const query = plainToClass(ErrorCardFindManyArgs, request.query);
    const results = await this.service.findErrorCards(params.id, {
      ...query,
      select: {
        createdAt: true,
        errorCount: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        id: true,

        studentProfile: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/errorCards")
  async connectErrorCards(
    @common.Param() params: FlashcardWhereUniqueInput,
    @common.Body() body: ErrorCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      errorCards: {
        connect: body,
      },
    };
    await this.service.updateFlashcard({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/errorCards")
  async updateErrorCards(
    @common.Param() params: FlashcardWhereUniqueInput,
    @common.Body() body: ErrorCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      errorCards: {
        set: body,
      },
    };
    await this.service.updateFlashcard({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/errorCards")
  async disconnectErrorCards(
    @common.Param() params: FlashcardWhereUniqueInput,
    @common.Body() body: ErrorCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      errorCards: {
        disconnect: body,
      },
    };
    await this.service.updateFlashcard({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/flashcardSessionEntries")
  @ApiNestedQuery(FlashcardSessionEntryFindManyArgs)
  async findFlashcardSessionEntries(
    @common.Req() request: Request,
    @common.Param() params: FlashcardWhereUniqueInput
  ): Promise<FlashcardSessionEntry[]> {
    const query = plainToClass(
      FlashcardSessionEntryFindManyArgs,
      request.query
    );
    const results = await this.service.findFlashcardSessionEntries(params.id, {
      ...query,
      select: {
        bookmarked: true,
        createdAt: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        flashcardSession: {
          select: {
            id: true,
          },
        },

        id: true,
        microbitsMarked: true,
        rating: true,
        timeSpent: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/flashcardSessionEntries")
  async connectFlashcardSessionEntries(
    @common.Param() params: FlashcardWhereUniqueInput,
    @common.Body() body: FlashcardSessionEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardSessionEntries: {
        connect: body,
      },
    };
    await this.service.updateFlashcard({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/flashcardSessionEntries")
  async updateFlashcardSessionEntries(
    @common.Param() params: FlashcardWhereUniqueInput,
    @common.Body() body: FlashcardSessionEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardSessionEntries: {
        set: body,
      },
    };
    await this.service.updateFlashcard({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/flashcardSessionEntries")
  async disconnectFlashcardSessionEntries(
    @common.Param() params: FlashcardWhereUniqueInput,
    @common.Body() body: FlashcardSessionEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flashcardSessionEntries: {
        disconnect: body,
      },
    };
    await this.service.updateFlashcard({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/microbits")
  @ApiNestedQuery(MicrobitFindManyArgs)
  async findMicrobits(
    @common.Req() request: Request,
    @common.Param() params: FlashcardWhereUniqueInput
  ): Promise<Microbit[]> {
    const query = plainToClass(MicrobitFindManyArgs, request.query);
    const results = await this.service.findMicrobits(params.id, {
      ...query,
      select: {
        createdAt: true,
        feedback: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        forgetCount: true,
        highlightedText: true,
        id: true,
        reviewCount: true,
        text: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/microbits")
  async connectMicrobits(
    @common.Param() params: FlashcardWhereUniqueInput,
    @common.Body() body: MicrobitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      microbits: {
        connect: body,
      },
    };
    await this.service.updateFlashcard({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/microbits")
  async updateMicrobits(
    @common.Param() params: FlashcardWhereUniqueInput,
    @common.Body() body: MicrobitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      microbits: {
        set: body,
      },
    };
    await this.service.updateFlashcard({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/microbits")
  async disconnectMicrobits(
    @common.Param() params: FlashcardWhereUniqueInput,
    @common.Body() body: MicrobitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      microbits: {
        disconnect: body,
      },
    };
    await this.service.updateFlashcard({
      where: params,
      data,
      select: { id: true },
    });
  }
}
