/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { ErrorCardListRelationFilter } from "../../errorCard/base/ErrorCardListRelationFilter";
import { FlashcardDeckWhereUniqueInput } from "../../flashcardDeck/base/FlashcardDeckWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { MicrobitListRelationFilter } from "../../microbit/base/MicrobitListRelationFilter";
import { JsonFilter } from "../../util/JsonFilter";

@InputType()
class FlashcardWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  backContent?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  cardType?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  correctOption?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ErrorCardListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ErrorCardListRelationFilter)
  @IsOptional()
  @Field(() => ErrorCardListRelationFilter, {
    nullable: true,
  })
  errorCards?: ErrorCardListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FlashcardDeckWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FlashcardDeckWhereUniqueInput)
  @IsOptional()
  @Field(() => FlashcardDeckWhereUniqueInput, {
    nullable: true,
  })
  flashcardDeck?: FlashcardDeckWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  frontContent?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  hint?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MicrobitListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MicrobitListRelationFilter)
  @IsOptional()
  @Field(() => MicrobitListRelationFilter, {
    nullable: true,
  })
  microbits?: MicrobitListRelationFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  options?: JsonFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  tags?: StringNullableFilter;
}

export { FlashcardWhereInput as FlashcardWhereInput };
