/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ErrorCard } from "./ErrorCard";
import { ErrorCardCountArgs } from "./ErrorCardCountArgs";
import { ErrorCardFindManyArgs } from "./ErrorCardFindManyArgs";
import { ErrorCardFindUniqueArgs } from "./ErrorCardFindUniqueArgs";
import { CreateErrorCardArgs } from "./CreateErrorCardArgs";
import { UpdateErrorCardArgs } from "./UpdateErrorCardArgs";
import { DeleteErrorCardArgs } from "./DeleteErrorCardArgs";
import { Flashcard } from "../../flashcard/base/Flashcard";
import { FlashcardDeck } from "../../flashcardDeck/base/FlashcardDeck";
import { StudentProfile } from "../../studentProfile/base/StudentProfile";
import { ErrorCardService } from "../errorCard.service";
@graphql.Resolver(() => ErrorCard)
export class ErrorCardResolverBase {
  constructor(protected readonly service: ErrorCardService) {}

  async _errorCardsMeta(
    @graphql.Args() args: ErrorCardCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ErrorCard])
  async errorCards(
    @graphql.Args() args: ErrorCardFindManyArgs
  ): Promise<ErrorCard[]> {
    return this.service.errorCards(args);
  }

  @graphql.Query(() => ErrorCard, { nullable: true })
  async errorCard(
    @graphql.Args() args: ErrorCardFindUniqueArgs
  ): Promise<ErrorCard | null> {
    const result = await this.service.errorCard(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ErrorCard)
  async createErrorCard(
    @graphql.Args() args: CreateErrorCardArgs
  ): Promise<ErrorCard> {
    return await this.service.createErrorCard({
      ...args,
      data: {
        ...args.data,

        flashcard: args.data.flashcard
          ? {
              connect: args.data.flashcard,
            }
          : undefined,

        flashcardDeck: args.data.flashcardDeck
          ? {
              connect: args.data.flashcardDeck,
            }
          : undefined,

        studentProfile: args.data.studentProfile
          ? {
              connect: args.data.studentProfile,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => ErrorCard)
  async updateErrorCard(
    @graphql.Args() args: UpdateErrorCardArgs
  ): Promise<ErrorCard | null> {
    try {
      return await this.service.updateErrorCard({
        ...args,
        data: {
          ...args.data,

          flashcard: args.data.flashcard
            ? {
                connect: args.data.flashcard,
              }
            : undefined,

          flashcardDeck: args.data.flashcardDeck
            ? {
                connect: args.data.flashcardDeck,
              }
            : undefined,

          studentProfile: args.data.studentProfile
            ? {
                connect: args.data.studentProfile,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ErrorCard)
  async deleteErrorCard(
    @graphql.Args() args: DeleteErrorCardArgs
  ): Promise<ErrorCard | null> {
    try {
      return await this.service.deleteErrorCard(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Flashcard, {
    nullable: true,
    name: "flashcard",
  })
  async getFlashcard(
    @graphql.Parent() parent: ErrorCard
  ): Promise<Flashcard | null> {
    const result = await this.service.getFlashcard(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => FlashcardDeck, {
    nullable: true,
    name: "flashcardDeck",
  })
  async getFlashcardDeck(
    @graphql.Parent() parent: ErrorCard
  ): Promise<FlashcardDeck | null> {
    const result = await this.service.getFlashcardDeck(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => StudentProfile, {
    nullable: true,
    name: "studentProfile",
  })
  async getStudentProfile(
    @graphql.Parent() parent: ErrorCard
  ): Promise<StudentProfile | null> {
    const result = await this.service.getStudentProfile(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
