/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ErrorCardService } from "../errorCard.service";
import { ErrorCardCreateInput } from "./ErrorCardCreateInput";
import { ErrorCard } from "./ErrorCard";
import { ErrorCardFindManyArgs } from "./ErrorCardFindManyArgs";
import { ErrorCardWhereUniqueInput } from "./ErrorCardWhereUniqueInput";
import { ErrorCardUpdateInput } from "./ErrorCardUpdateInput";

export class ErrorCardControllerBase {
  constructor(protected readonly service: ErrorCardService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ErrorCard })
  async createErrorCard(
    @common.Body() data: ErrorCardCreateInput
  ): Promise<ErrorCard> {
    return await this.service.createErrorCard({
      data: {
        ...data,

        flashcard: data.flashcard
          ? {
              connect: data.flashcard,
            }
          : undefined,

        flashcardDeck: data.flashcardDeck
          ? {
              connect: data.flashcardDeck,
            }
          : undefined,

        studentProfile: data.studentProfile
          ? {
              connect: data.studentProfile,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        errorCount: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        id: true,

        studentProfile: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ErrorCard] })
  @ApiNestedQuery(ErrorCardFindManyArgs)
  async errorCards(@common.Req() request: Request): Promise<ErrorCard[]> {
    const args = plainToClass(ErrorCardFindManyArgs, request.query);
    return this.service.errorCards({
      ...args,
      select: {
        createdAt: true,
        errorCount: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        id: true,

        studentProfile: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ErrorCard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async errorCard(
    @common.Param() params: ErrorCardWhereUniqueInput
  ): Promise<ErrorCard | null> {
    const result = await this.service.errorCard({
      where: params,
      select: {
        createdAt: true,
        errorCount: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        flashcardDeck: {
          select: {
            id: true,
          },
        },

        id: true,

        studentProfile: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ErrorCard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateErrorCard(
    @common.Param() params: ErrorCardWhereUniqueInput,
    @common.Body() data: ErrorCardUpdateInput
  ): Promise<ErrorCard | null> {
    try {
      return await this.service.updateErrorCard({
        where: params,
        data: {
          ...data,

          flashcard: data.flashcard
            ? {
                connect: data.flashcard,
              }
            : undefined,

          flashcardDeck: data.flashcardDeck
            ? {
                connect: data.flashcardDeck,
              }
            : undefined,

          studentProfile: data.studentProfile
            ? {
                connect: data.studentProfile,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          errorCount: true,

          flashcard: {
            select: {
              id: true,
            },
          },

          flashcardDeck: {
            select: {
              id: true,
            },
          },

          id: true,

          studentProfile: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ErrorCard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteErrorCard(
    @common.Param() params: ErrorCardWhereUniqueInput
  ): Promise<ErrorCard | null> {
    try {
      return await this.service.deleteErrorCard({
        where: params,
        select: {
          createdAt: true,
          errorCount: true,

          flashcard: {
            select: {
              id: true,
            },
          },

          flashcardDeck: {
            select: {
              id: true,
            },
          },

          id: true,

          studentProfile: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
