/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ErrorCard as PrismaErrorCard,
  Flashcard as PrismaFlashcard,
  FlashcardDeck as PrismaFlashcardDeck,
  StudentProfile as PrismaStudentProfile,
} from "@prisma/client";

export class ErrorCardServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ErrorCardCountArgs, "select">
  ): Promise<number> {
    return this.prisma.errorCard.count(args);
  }

  async errorCards(
    args: Prisma.ErrorCardFindManyArgs
  ): Promise<PrismaErrorCard[]> {
    return this.prisma.errorCard.findMany(args);
  }
  async errorCard(
    args: Prisma.ErrorCardFindUniqueArgs
  ): Promise<PrismaErrorCard | null> {
    return this.prisma.errorCard.findUnique(args);
  }
  async createErrorCard(
    args: Prisma.ErrorCardCreateArgs
  ): Promise<PrismaErrorCard> {
    return this.prisma.errorCard.create(args);
  }
  async updateErrorCard(
    args: Prisma.ErrorCardUpdateArgs
  ): Promise<PrismaErrorCard> {
    return this.prisma.errorCard.update(args);
  }
  async deleteErrorCard(
    args: Prisma.ErrorCardDeleteArgs
  ): Promise<PrismaErrorCard> {
    return this.prisma.errorCard.delete(args);
  }

  async getFlashcard(parentId: string): Promise<PrismaFlashcard | null> {
    return this.prisma.errorCard
      .findUnique({
        where: { id: parentId },
      })
      .flashcard();
  }

  async getFlashcardDeck(
    parentId: string
  ): Promise<PrismaFlashcardDeck | null> {
    return this.prisma.errorCard
      .findUnique({
        where: { id: parentId },
      })
      .flashcardDeck();
  }

  async getStudentProfile(
    parentId: string
  ): Promise<PrismaStudentProfile | null> {
    return this.prisma.errorCard
      .findUnique({
        where: { id: parentId },
      })
      .studentProfile();
  }
}
