/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FlashcardSessionEntry } from "./FlashcardSessionEntry";
import { FlashcardSessionEntryCountArgs } from "./FlashcardSessionEntryCountArgs";
import { FlashcardSessionEntryFindManyArgs } from "./FlashcardSessionEntryFindManyArgs";
import { FlashcardSessionEntryFindUniqueArgs } from "./FlashcardSessionEntryFindUniqueArgs";
import { CreateFlashcardSessionEntryArgs } from "./CreateFlashcardSessionEntryArgs";
import { UpdateFlashcardSessionEntryArgs } from "./UpdateFlashcardSessionEntryArgs";
import { DeleteFlashcardSessionEntryArgs } from "./DeleteFlashcardSessionEntryArgs";
import { Flashcard } from "../../flashcard/base/Flashcard";
import { FlashcardSession } from "../../flashcardSession/base/FlashcardSession";
import { FlashcardSessionEntryService } from "../flashcardSessionEntry.service";
@graphql.Resolver(() => FlashcardSessionEntry)
export class FlashcardSessionEntryResolverBase {
  constructor(protected readonly service: FlashcardSessionEntryService) {}

  async _flashcardSessionEntriesMeta(
    @graphql.Args() args: FlashcardSessionEntryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FlashcardSessionEntry])
  async flashcardSessionEntries(
    @graphql.Args() args: FlashcardSessionEntryFindManyArgs
  ): Promise<FlashcardSessionEntry[]> {
    return this.service.flashcardSessionEntries(args);
  }

  @graphql.Query(() => FlashcardSessionEntry, { nullable: true })
  async flashcardSessionEntry(
    @graphql.Args() args: FlashcardSessionEntryFindUniqueArgs
  ): Promise<FlashcardSessionEntry | null> {
    const result = await this.service.flashcardSessionEntry(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FlashcardSessionEntry)
  async createFlashcardSessionEntry(
    @graphql.Args() args: CreateFlashcardSessionEntryArgs
  ): Promise<FlashcardSessionEntry> {
    return await this.service.createFlashcardSessionEntry({
      ...args,
      data: {
        ...args.data,

        flashcard: args.data.flashcard
          ? {
              connect: args.data.flashcard,
            }
          : undefined,

        flashcardSession: args.data.flashcardSession
          ? {
              connect: args.data.flashcardSession,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => FlashcardSessionEntry)
  async updateFlashcardSessionEntry(
    @graphql.Args() args: UpdateFlashcardSessionEntryArgs
  ): Promise<FlashcardSessionEntry | null> {
    try {
      return await this.service.updateFlashcardSessionEntry({
        ...args,
        data: {
          ...args.data,

          flashcard: args.data.flashcard
            ? {
                connect: args.data.flashcard,
              }
            : undefined,

          flashcardSession: args.data.flashcardSession
            ? {
                connect: args.data.flashcardSession,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FlashcardSessionEntry)
  async deleteFlashcardSessionEntry(
    @graphql.Args() args: DeleteFlashcardSessionEntryArgs
  ): Promise<FlashcardSessionEntry | null> {
    try {
      return await this.service.deleteFlashcardSessionEntry(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Flashcard, {
    nullable: true,
    name: "flashcard",
  })
  async getFlashcard(
    @graphql.Parent() parent: FlashcardSessionEntry
  ): Promise<Flashcard | null> {
    const result = await this.service.getFlashcard(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => FlashcardSession, {
    nullable: true,
    name: "flashcardSession",
  })
  async getFlashcardSession(
    @graphql.Parent() parent: FlashcardSessionEntry
  ): Promise<FlashcardSession | null> {
    const result = await this.service.getFlashcardSession(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
