/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  FlashcardSessionEntry as PrismaFlashcardSessionEntry,
  Flashcard as PrismaFlashcard,
  FlashcardSession as PrismaFlashcardSession,
} from "@prisma/client";

export class FlashcardSessionEntryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FlashcardSessionEntryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.flashcardSessionEntry.count(args);
  }

  async flashcardSessionEntries(
    args: Prisma.FlashcardSessionEntryFindManyArgs
  ): Promise<PrismaFlashcardSessionEntry[]> {
    return this.prisma.flashcardSessionEntry.findMany(args);
  }
  async flashcardSessionEntry(
    args: Prisma.FlashcardSessionEntryFindUniqueArgs
  ): Promise<PrismaFlashcardSessionEntry | null> {
    return this.prisma.flashcardSessionEntry.findUnique(args);
  }
  async createFlashcardSessionEntry(
    args: Prisma.FlashcardSessionEntryCreateArgs
  ): Promise<PrismaFlashcardSessionEntry> {
    return this.prisma.flashcardSessionEntry.create(args);
  }
  async updateFlashcardSessionEntry(
    args: Prisma.FlashcardSessionEntryUpdateArgs
  ): Promise<PrismaFlashcardSessionEntry> {
    return this.prisma.flashcardSessionEntry.update(args);
  }
  async deleteFlashcardSessionEntry(
    args: Prisma.FlashcardSessionEntryDeleteArgs
  ): Promise<PrismaFlashcardSessionEntry> {
    return this.prisma.flashcardSessionEntry.delete(args);
  }

  async getFlashcard(parentId: string): Promise<PrismaFlashcard | null> {
    return this.prisma.flashcardSessionEntry
      .findUnique({
        where: { id: parentId },
      })
      .flashcard();
  }

  async getFlashcardSession(
    parentId: string
  ): Promise<PrismaFlashcardSession | null> {
    return this.prisma.flashcardSessionEntry
      .findUnique({
        where: { id: parentId },
      })
      .flashcardSession();
  }
}
