/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FlashcardSessionEntryService } from "../flashcardSessionEntry.service";
import { FlashcardSessionEntryCreateInput } from "./FlashcardSessionEntryCreateInput";
import { FlashcardSessionEntry } from "./FlashcardSessionEntry";
import { FlashcardSessionEntryFindManyArgs } from "./FlashcardSessionEntryFindManyArgs";
import { FlashcardSessionEntryWhereUniqueInput } from "./FlashcardSessionEntryWhereUniqueInput";
import { FlashcardSessionEntryUpdateInput } from "./FlashcardSessionEntryUpdateInput";

export class FlashcardSessionEntryControllerBase {
  constructor(protected readonly service: FlashcardSessionEntryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FlashcardSessionEntry })
  async createFlashcardSessionEntry(
    @common.Body() data: FlashcardSessionEntryCreateInput
  ): Promise<FlashcardSessionEntry> {
    return await this.service.createFlashcardSessionEntry({
      data: {
        ...data,

        flashcard: data.flashcard
          ? {
              connect: data.flashcard,
            }
          : undefined,

        flashcardSession: data.flashcardSession
          ? {
              connect: data.flashcardSession,
            }
          : undefined,
      },
      select: {
        bookmarked: true,
        createdAt: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        flashcardSession: {
          select: {
            id: true,
          },
        },

        id: true,
        microbitsMarked: true,
        rating: true,
        timeSpent: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FlashcardSessionEntry] })
  @ApiNestedQuery(FlashcardSessionEntryFindManyArgs)
  async flashcardSessionEntries(
    @common.Req() request: Request
  ): Promise<FlashcardSessionEntry[]> {
    const args = plainToClass(FlashcardSessionEntryFindManyArgs, request.query);
    return this.service.flashcardSessionEntries({
      ...args,
      select: {
        bookmarked: true,
        createdAt: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        flashcardSession: {
          select: {
            id: true,
          },
        },

        id: true,
        microbitsMarked: true,
        rating: true,
        timeSpent: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FlashcardSessionEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async flashcardSessionEntry(
    @common.Param() params: FlashcardSessionEntryWhereUniqueInput
  ): Promise<FlashcardSessionEntry | null> {
    const result = await this.service.flashcardSessionEntry({
      where: params,
      select: {
        bookmarked: true,
        createdAt: true,

        flashcard: {
          select: {
            id: true,
          },
        },

        flashcardSession: {
          select: {
            id: true,
          },
        },

        id: true,
        microbitsMarked: true,
        rating: true,
        timeSpent: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FlashcardSessionEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFlashcardSessionEntry(
    @common.Param() params: FlashcardSessionEntryWhereUniqueInput,
    @common.Body() data: FlashcardSessionEntryUpdateInput
  ): Promise<FlashcardSessionEntry | null> {
    try {
      return await this.service.updateFlashcardSessionEntry({
        where: params,
        data: {
          ...data,

          flashcard: data.flashcard
            ? {
                connect: data.flashcard,
              }
            : undefined,

          flashcardSession: data.flashcardSession
            ? {
                connect: data.flashcardSession,
              }
            : undefined,
        },
        select: {
          bookmarked: true,
          createdAt: true,

          flashcard: {
            select: {
              id: true,
            },
          },

          flashcardSession: {
            select: {
              id: true,
            },
          },

          id: true,
          microbitsMarked: true,
          rating: true,
          timeSpent: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FlashcardSessionEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFlashcardSessionEntry(
    @common.Param() params: FlashcardSessionEntryWhereUniqueInput
  ): Promise<FlashcardSessionEntry | null> {
    try {
      return await this.service.deleteFlashcardSessionEntry({
        where: params,
        select: {
          bookmarked: true,
          createdAt: true,

          flashcard: {
            select: {
              id: true,
            },
          },

          flashcardSession: {
            select: {
              id: true,
            },
          },

          id: true,
          microbitsMarked: true,
          rating: true,
          timeSpent: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
