/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, CategoryTag as PrismaCategoryTag } from "@prisma/client";

export class CategoryTagServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CategoryTagCountArgs, "select">
  ): Promise<number> {
    return this.prisma.categoryTag.count(args);
  }

  async categoryTags(
    args: Prisma.CategoryTagFindManyArgs
  ): Promise<PrismaCategoryTag[]> {
    return this.prisma.categoryTag.findMany(args);
  }
  async categoryTag(
    args: Prisma.CategoryTagFindUniqueArgs
  ): Promise<PrismaCategoryTag | null> {
    return this.prisma.categoryTag.findUnique(args);
  }
  async createCategoryTag(
    args: Prisma.CategoryTagCreateArgs
  ): Promise<PrismaCategoryTag> {
    return this.prisma.categoryTag.create(args);
  }
  async updateCategoryTag(
    args: Prisma.CategoryTagUpdateArgs
  ): Promise<PrismaCategoryTag> {
    return this.prisma.categoryTag.update(args);
  }
  async deleteCategoryTag(
    args: Prisma.CategoryTagDeleteArgs
  ): Promise<PrismaCategoryTag> {
    return this.prisma.categoryTag.delete(args);
  }
}
