/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CategoryTagService } from "../categoryTag.service";
import { CategoryTagCreateInput } from "./CategoryTagCreateInput";
import { CategoryTag } from "./CategoryTag";
import { CategoryTagFindManyArgs } from "./CategoryTagFindManyArgs";
import { CategoryTagWhereUniqueInput } from "./CategoryTagWhereUniqueInput";
import { CategoryTagUpdateInput } from "./CategoryTagUpdateInput";

export class CategoryTagControllerBase {
  constructor(protected readonly service: CategoryTagService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CategoryTag })
  async createCategoryTag(
    @common.Body() data: CategoryTagCreateInput
  ): Promise<CategoryTag> {
    return await this.service.createCategoryTag({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        parent: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CategoryTag] })
  @ApiNestedQuery(CategoryTagFindManyArgs)
  async categoryTags(@common.Req() request: Request): Promise<CategoryTag[]> {
    const args = plainToClass(CategoryTagFindManyArgs, request.query);
    return this.service.categoryTags({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        parent: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CategoryTag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async categoryTag(
    @common.Param() params: CategoryTagWhereUniqueInput
  ): Promise<CategoryTag | null> {
    const result = await this.service.categoryTag({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        parent: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CategoryTag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCategoryTag(
    @common.Param() params: CategoryTagWhereUniqueInput,
    @common.Body() data: CategoryTagUpdateInput
  ): Promise<CategoryTag | null> {
    try {
      return await this.service.updateCategoryTag({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          parent: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CategoryTag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCategoryTag(
    @common.Param() params: CategoryTagWhereUniqueInput
  ): Promise<CategoryTag | null> {
    try {
      return await this.service.deleteCategoryTag({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          parent: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
