/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CategoryTag } from "./CategoryTag";
import { CategoryTagCountArgs } from "./CategoryTagCountArgs";
import { CategoryTagFindManyArgs } from "./CategoryTagFindManyArgs";
import { CategoryTagFindUniqueArgs } from "./CategoryTagFindUniqueArgs";
import { CreateCategoryTagArgs } from "./CreateCategoryTagArgs";
import { UpdateCategoryTagArgs } from "./UpdateCategoryTagArgs";
import { DeleteCategoryTagArgs } from "./DeleteCategoryTagArgs";
import { CategoryTagService } from "../categoryTag.service";
@graphql.Resolver(() => CategoryTag)
export class CategoryTagResolverBase {
  constructor(protected readonly service: CategoryTagService) {}

  async _categoryTagsMeta(
    @graphql.Args() args: CategoryTagCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CategoryTag])
  async categoryTags(
    @graphql.Args() args: CategoryTagFindManyArgs
  ): Promise<CategoryTag[]> {
    return this.service.categoryTags(args);
  }

  @graphql.Query(() => CategoryTag, { nullable: true })
  async categoryTag(
    @graphql.Args() args: CategoryTagFindUniqueArgs
  ): Promise<CategoryTag | null> {
    const result = await this.service.categoryTag(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CategoryTag)
  async createCategoryTag(
    @graphql.Args() args: CreateCategoryTagArgs
  ): Promise<CategoryTag> {
    return await this.service.createCategoryTag({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => CategoryTag)
  async updateCategoryTag(
    @graphql.Args() args: UpdateCategoryTagArgs
  ): Promise<CategoryTag | null> {
    try {
      return await this.service.updateCategoryTag({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CategoryTag)
  async deleteCategoryTag(
    @graphql.Args() args: DeleteCategoryTagArgs
  ): Promise<CategoryTag | null> {
    try {
      return await this.service.deleteCategoryTag(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
